<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#FILTER-Missing-values" data-toc-modified-id="FILTER-Missing-values-1">FILTER Missing values</a></span></li><li><span><a href="#EDA:-interaction_types" data-toc-modified-id="EDA:-interaction_types-2">EDA: interaction_types</a></span></li><li><span><a href="#EDA-interaction_source_db_name" data-toc-modified-id="EDA-interaction_source_db_name-3">EDA interaction_source_db_name</a></span></li><li><span><a href="#EDA-drug_is_immunotherapy" data-toc-modified-id="EDA-drug_is_immunotherapy-4">EDA drug_is_immunotherapy</a></span></li><li><span><a href="#FILTER,-clean-Namespaces" data-toc-modified-id="FILTER,-clean-Namespaces-5">FILTER, clean Namespaces</a></span></li><li><span><a href="#Cleaning-interaction_types" data-toc-modified-id="Cleaning-interaction_types-6">Cleaning interaction_types</a></span><ul class="toc-item"><li><span><a href="#EDA-&quot;|-delimited&quot;-values" data-toc-modified-id="EDA-&quot;|-delimited&quot;-values-6.1">EDA "|-delimited" values</a></span></li><li><span><a href="#Split-&quot;|-delimited&quot;" data-toc-modified-id="Split-&quot;|-delimited&quot;-6.2">Split "|-delimited"</a></span></li></ul></li><li><span><a href="#EDA-Merging-by-gene-drug-pairs" data-toc-modified-id="EDA-Merging-by-gene-drug-pairs-7">EDA Merging by gene-drug pairs</a></span><ul class="toc-item"><li><span><a href="#interaction_types" data-toc-modified-id="interaction_types-7.1">interaction_types</a></span></li><li><span><a href="#interaction_source_db_name" data-toc-modified-id="interaction_source_db_name-7.2">interaction_source_db_name</a></span></li></ul></li><li><span><a href="#EDA-Merging-by-gene-drug-interaction_type-combos" data-toc-modified-id="EDA-Merging-by-gene-drug-interaction_type-combos-8">EDA Merging by gene-drug-interaction_type combos</a></span></li><li><span><a href="#Merge-by-drug-gene-mod_type-combos" data-toc-modified-id="Merge-by-drug-gene-mod_type-combos-9">Merge by drug-gene-mod_type combos</a></span></li><li><span><a href="#Special-logic" data-toc-modified-id="Special-logic-10">Special logic</a></span><ul class="toc-item"><li><span><a href="#sources" data-toc-modified-id="sources-10.1">sources</a></span></li><li><span><a href="#scores-logic" data-toc-modified-id="scores-logic-10.2">scores logic</a></span></li></ul></li><li><span><a href="#For-comparing-to-pipeline-output" data-toc-modified-id="For-comparing-to-pipeline-output-11">For comparing to pipeline output</a></span></li></ul></div>

# DGIdb notebook: EDA + code dev

In [1]:
## for notebook only 

## allows multiple lines of code to print from one code block
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## for printing
from pprint import pprint, pp

## for loading locally-stored files
import pathlib

In [2]:
import pandas as pd

## NOT for parser: for viewing df only
pd.options.display.max_columns = None
pd.set_option('display.max_colwidth', None)

<div class="alert alert-block alert-danger">

UPDATE 2026-09
    
This notebook was originally written using the **2024-Dec** interactions.tsv from https://dgidb.org/downloads. The version can be based on the HEAD request "last modified" date or the header lines (Data version). 
    
<br>

There is no longer a "latest" interactions.tsv link.

The 2026-09 file has two header lines showing the "data version" and "DGIdb version". While the DGIdb version is semantic versioning, I suspect we should use the DATA version instead (month-year date). 

```
# Data version: 2026-09
# DGIdb version: v.5.0.13
```

In [3]:
## path to raw resource file
interactions_path = pathlib.Path.home().joinpath("Desktop", 
                                                 "DGIdb_files",
                                                 "2026-09-interactions.tsv")

In [4]:
## load file in pandas directly

## skip first two lines (comments)
## setting parameter comment="#" causes a bug
##   because some lines have # in the names. param causes rest of line to be NA
df = pd.read_table(interactions_path, header=2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122904 entries, 0 to 122903
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   gene_claim_name                122897 non-null  object
 1   gene_concept_id                114012 non-null  object
 2   gene_name                      114012 non-null  object
 3   drug_claim_name                122904 non-null  object
 4   drug_concept_id                108125 non-null  object
 5   drug_name                      108125 non-null  object
 6   drug_is_approved               108125 non-null  object
 7   drug_is_immunotherapy          108125 non-null  object
 8   drug_is_antineoplastic         108125 non-null  object
 9   interaction_source_db_name     122904 non-null  object
 10  interaction_source_db_version  122904 non-null  object
 11  interaction_types              37067 non-null   object
 12  interaction_score              101109 non-null  float64
 13  drug_specificity_score         101109 non-null  float64
 14  gene_specificity_score         101109 non-null  float64
 15  evidence_score                 101109 non-null  float64
dtypes: float64(4), object(12)
memory usage: 15.0+ MB

In [6]:
## some rows are missing lots of values because drug wasn't resolved to an ID
df.head()

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
0,RIBONUCLEOSIDE-DIPHOSPHATE REDUCTASE M2,hgnc:10452,RRM2,Gemcitabine prodrug,NaN,NaN,NaN,NaN,NaN,TTD,2020.06.01,NaN,NaN,NaN,NaN,NaN
1,RIBONUCLEOSIDE-DIPHOSPHATE REDUCTASE M2,hgnc:10452,RRM2,Gemcitabine,rxcui:12574,GEMCITABINE,True,False,True,TTD,2020.06.01,NaN,0.134548,0.042170,0.797655,4.0
2,RIBONUCLEOSIDE-DIPHOSPHATE REDUCTASE M2,hgnc:10452,RRM2,NKP-46,NaN,NaN,NaN,NaN,NaN,TTD,2020.06.01,NaN,NaN,NaN,NaN,NaN
3,RIBONUCLEOSIDE-DIPHOSPHATE REDUCTASE M2,hgnc:10452,RRM2,Triapine,ncit:C2242,TRIAPINE,False,False,True,TTD,2020.06.01,NaN,1.950947,0.611463,0.797655,4.0
4,RIBONUCLEOSIDE-DIPHOSPHATE REDUCTASE M2,hgnc:10452,RRM2,CO-101,chembl:CHEMBL3039516,GEMCITABINE ELAIDATE,False,False,False,TTD,2020.06.01,NaN,2.926421,3.668778,0.797655,1.0

## FILTER Missing values

Review:
* **All of the columns have some missing values**
* the entity ID columns `gene_concept_id` and `drug_concept_id` are missing thousands of values - even though DGIdb did an [entity-resolving/common-ID-assignment step](https://dgidb.org/about/overview/grouping). 
* BUT it is expected that `interaction_types` is missing values, since not all sources will assign specific relationship types (ex: inhibitor).

In [7]:
## EDA - going through columns looking at missing values

# df[df["gene_concept_id"].isna()]

# df[df["drug_concept_id"].isna()]

df[df["interaction_source_db_name"].isna()]

Empty DataFrame
Columns: [gene_claim_name, gene_concept_id, gene_name, drug_claim_name, drug_concept_id, drug_name, drug_is_approved, drug_is_immunotherapy, drug_is_antineoplastic, interaction_source_db_name, interaction_source_db_version, interaction_types, interaction_score, drug_specificity_score, gene_specificity_score, evidence_score]
Index: []

<div class="alert alert-block alert-success">

**DECISION**: drop rows with NA in `gene_concept_id` OR `drug_concept_id`.

In [8]:
## PARTIAL INCLUDE IN PARSER

## logs

## number of rows left after dropping NAs
## default is remove if any column has NA for the row
have_values = df.dropna(subset=["gene_concept_id", 
                                "drug_concept_id"]).shape[0]
print(f"{have_values} rows ({have_values / df.shape[0]:.1%}) kept (have both entity IDs)")
print("\n")

## gene IDs
have_gene_id = df["gene_concept_id"].notna().sum()
print(f"{have_gene_id} rows have gene IDs: {have_gene_id / df.shape[0]:.1%}")

## drug IDs
have_drug_id = df["drug_concept_id"].notna().sum()
print(f"{have_drug_id} rows have drug IDs: {have_drug_id / df.shape[0]:.1%}")

101109 rows (82.3%) kept (have both entity IDs)


114012 rows have gene IDs: 92.8%
108125 rows have drug IDs: 88.0%

In [9]:
## EDA ONLY
## save set of interaction_types before filtering, to compare to after

starting_interact_types = set(df["interaction_types"].unique())
len(starting_interact_types)

34

In [10]:
## INCLUDE IN PARSER

## drop rows, check
## default is remove if any column has NA for the row
df.dropna(subset=["gene_concept_id", "drug_concept_id"], 
          ignore_index=True, 
          inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101109 entries, 0 to 101108
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   gene_claim_name                101102 non-null  object
 1   gene_concept_id                101109 non-null  object
 2   gene_name                      101109 non-null  object
 3   drug_claim_name                101109 non-null  object
 4   drug_concept_id                101109 non-null  object
 5   drug_name                      101109 non-null  object
 6   drug_is_approved               101109 non-null  object
 7   drug_is_immunotherapy          101109 non-null  object
 8   drug_is_antineoplastic         101109 non-null  object
 9   interaction_source_db_name     101109 non-null  object
 10  interaction_source_db_version  101109 non-null  object
 11  interaction_types              31831 non-null   object
 12  interaction_score              101109 non-null  float64
 13  drug_specificity_score         101109 non-null  float64
 14  gene_specificity_score         101109 non-null  float64
 15  evidence_score                 101109 non-null  float64
dtypes: float64(4), object(12)
memory usage: 12.3+ MB

## EDA: interaction_types

[2026-09-16 with 2026-09 data]

Doing a little EDA here, when data still has starting set of interaction_types values.

In [11]:
## compare before-after

starting_interact_types == set(df["interaction_types"].unique())

True

In [12]:
df["interaction_types"].nunique(dropna=False)

df["interaction_types"].value_counts(dropna=False).sort_index()

34

interaction_types
activator                      617
activator|blocker                2
activator|inhibitor              3
agonist                       6005
agonist|inhibitor               18
agonist|modulator                1
antibody                       347
antibody|immunotherapy           5
antisense oligonucleotide        4
binder                         279
blocker                       1849
blocker|activator                4
blocker|inhibitor                5
blocker|modulator                1
cleavage                        85
cleavage|inhibitor               1
immunotherapy                    3
immunotherapy|antibody           3
inhibitor                    19762
inhibitor|activator              2
inhibitor|agonist               18
inhibitor|binder                 1
inhibitor|blocker                1
inhibitor|modulator              4
inverse agonist                 37
modulator                     1295
modulator|agonist                3
modulator|inhibitor              4
negative modulator             148
other/unknown                  219
positive modulator            1014
potentiator                     51
vaccine                         40
NaN                          69278
Name: count, dtype: int64

In [13]:
df_piped_types = df[df["interaction_types"].str.contains("\\|", na=False)].copy()

print(f"{df_piped_types.shape[0]} rows with |-delimited interaction_types" + 
      f": {df_piped_types.shape[0] / df.shape[0]:.3%}")

df_piped_types.head()

76 rows with |-delimited interaction_types: 0.075%

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
1165,IUPHAR.RECEPTOR:627,hgnc:8910,PGR,IUPHAR.LIGAND:2805,rxcui:6964,MIFEPRISTONE,True,False,False,GuideToPharmacology,2026.2,inhibitor|agonist,0.093946,0.131028,0.143399,5.0
1174,IUPHAR.RECEPTOR:627,hgnc:8910,PGR,IUPHAR.LIGAND:7460,rxcui:1005920,ULIPRISTAL ACETATE,True,False,False,GuideToPharmacology,2026.2,agonist|inhibitor,3.156589,3.668778,0.143399,6.0
2991,IUPHAR.RECEPTOR:484,hgnc:8537,P2RX7,IUPHAR.LIGAND:10504,iuphar.ligand:10504,GSK1482160,False,False,False,GuideToPharmacology,2026.2,inhibitor|modulator,4.256612,3.668778,0.386742,3.0
2999,IUPHAR.RECEPTOR:484,hgnc:8537,P2RX7,IUPHAR.LIGAND:9021,iuphar.ligand:9021,AZ10606120,False,False,False,GuideToPharmacology,2026.2,modulator|inhibitor,2.837741,3.668778,0.386742,2.0
4087,IUPHAR.RECEPTOR:277,hgnc:3167,S1PR3,IUPHAR.LIGAND:9494,iuphar.ligand:9494,CYM-5541,False,False,False,GuideToPharmacology,2026.2,agonist|modulator,4.071542,3.668778,0.554891,2.0

In [14]:
df_piped_types["interaction_types"].nunique()

df_piped_types["interaction_types"].value_counts().sort_index()

17

interaction_types
activator|blocker          2
activator|inhibitor        3
agonist|inhibitor         18
agonist|modulator          1
antibody|immunotherapy     5
blocker|activator          4
blocker|inhibitor          5
blocker|modulator          1
cleavage|inhibitor         1
immunotherapy|antibody     3
inhibitor|activator        2
inhibitor|agonist         18
inhibitor|binder           1
inhibitor|blocker          1
inhibitor|modulator        4
modulator|agonist          3
modulator|inhibitor        4
Name: count, dtype: int64

**REVIEW**

**Opposing:**
* activator|blocker
* blocker|activator
* activator|inhibitor
* inhibitor|activator
* agonist|inhibitor
* inhibitor|agonist

**Close:**
* blocker|inhibitor
* inhibitor|blocker
* cleavage|inhibitor 

**One is kinda a subclass of the other?**
* agonist|modulator
* modulator|agonist
* inhibitor|modulator
* modulator|inhibitor
* blocker|modulator
* inhibitor|binder 

**Identical?**
* antibody|immunotherapy
* immunotherapy|antibody

In [15]:
## are the "flipped order" types the same data? esp when same row count?
## NO - based on the few pairs I reviewed

df_piped_types[df_piped_types["interaction_types"] == "activator|inhibitor"]
df_piped_types[df_piped_types["interaction_types"] == "inhibitor|activator"]

# df_multi_types[df_multi_types["interaction_types"] == "agonist|modulator"]
# df_multi_types[df_multi_types["interaction_types"] == "modulator|agonist"]

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
16020,IUPHAR.RECEPTOR:747,hgnc:10483,RYR1,IUPHAR.LIGAND:707,iuphar.ligand:707,CA2+,False,False,False,GuideToPharmacology,2026.2,activator|inhibitor,0.047584,0.089482,0.531770,1.0
22474,BRAF,hgnc:1097,BRAF,VEMURAFENIB,rxcui:1147220,VEMURAFENIB,True,False,True,MyCancerGenomeClinicalTrial,30-Feburary-2014,activator|inhibitor,1.114827,0.087352,0.050049,255.0
34868,IUPHAR.RECEPTOR:748,hgnc:10484,RYR2,IUPHAR.LIGAND:707,iuphar.ligand:707,CA2+,False,False,False,GuideToPharmacology,2026.2,activator|inhibitor,0.103820,0.089482,1.160226,1.0

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
63372,IUPHAR.RECEPTOR:749,hgnc:10485,RYR3,IUPHAR.LIGAND:707,iuphar.ligand:707,CA2+,False,False,False,GuideToPharmacology,2026.2,inhibitor|activator,0.126891,0.089482,1.418054,1.0
67379,IUPHAR.RECEPTOR:381,hgnc:6290,KCNN1,IUPHAR.LIGAND:9314,iuphar.ligand:9314,CM-TPMF,False,False,False,GuideToPharmacology,2026.2,inhibitor|activator,1.950947,3.668778,0.531770,1.0

In [31]:
## from only 4 resources, mostly GuideToPharmacology

df_piped_types["interaction_source_db_name"].value_counts()

interaction_source_db_name
GuideToPharmacology            64
MyCancerGenome                  8
ChEMBL                          3
MyCancerGenomeClinicalTrial     1
Name: count, dtype: int64

## EDA interaction_source_db_name

aka "underlying sources". 
These are all single-values. 

Compared to the [website's "Interaction Sources"](https://dgidb.org/browse/sources), data has [all sources] - DrugBank. 
* On DrugBank, website actually doesn't have any "interaction claim" counts
* NCI has a link to broken webpage https://wiki.nci.nih.gov/spaces/cageneindex/overview. I think "cageneindex" stands for Cancer Gene Index from the National Cancer Institute, which is a defunct resource?

In [16]:
df["interaction_source_db_name"].nunique()

df["interaction_source_db_name"].value_counts().sort_index()

24

interaction_source_db_name
CGI                                  344
CIViC                               1095
CKB-CORE                            1798
COSMIC                                34
CancerCommons                        106
ChEMBL                             13027
ClearityFoundationBiomarkers         160
ClearityFoundationClinicalTrial      239
ClinPGx                             5650
DTC                                23872
DoCM                                  72
Drug Repurposing Hub               12734
FDA                                  402
GuideToPharmacology                17105
MOAlmanac                            203
MyCancerGenome                       803
MyCancerGenomeClinicalTrial          314
NCI                                 6040
OncoKB                               146
PRISM                               4411
TALC                                 564
TEND                                2242
TTD                                 5151
TdgClinicalTrial                    4597
Name: count, dtype: int64

In [21]:
df[df["interaction_source_db_name"] == "PRISM"]

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
66,TMEM62,hgnc:26269,TMEM62,elesclomol,ncit:C75291,ELESCLOMOL,False,False,False,PRISM,20-Jan-2020,NaN,7.803789,0.611463,12.762486,1.0
129,PDRG1,hgnc:16119,PDRG1,NVP-TAE226,iuphar.ligand:9382,NVP-TAE 226,False,False,True,PRISM,20-Jan-2020,NaN,1.232177,0.193094,6.381243,1.0
130,PDRG1,hgnc:16119,PDRG1,BMS-754807,drugbank:DB15399,BMS-754807,False,False,True,PRISM,20-Jan-2020,NaN,2.926421,0.458597,6.381243,1.0
161,RXRG,hgnc:10479,RXRG,GDC-0879,iuphar.ligand:5681,GDC-0879,False,False,True,PRISM,20-Jan-2020,NaN,0.225109,0.229299,0.981730,1.0
162,RXRG,hgnc:10479,RXRG,broxuridine,ncit:C318,BROXURIDINE,False,False,False,PRISM,20-Jan-2020,NaN,0.211868,0.215810,0.981730,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99912,ZNF491,hgnc:23706,ZNF491,nonoxynol-9,rxcui:53750,NONOXYNOL-9,True,False,False,PRISM,20-Jan-2020,NaN,0.650316,0.458597,1.418054,1.0
99918,SAMD1,hgnc:17958,SAMD1,barasertib,ncit:C62502,BARASERTIB,False,False,True,PRISM,20-Jan-2020,NaN,2.926421,0.229299,12.762486,1.0
99922,FBLN7,hgnc:26740,FBLN7,spironolactone,rxcui:9997,SPIRONOLACTONE,True,False,False,PRISM,20-Jan-2020,NaN,1.142018,0.089482,12.762486,1.0
99987,FASTKD5,hgnc:25790,FASTKD5,foretinib,ncit:C80058,FORETINIB,False,False,True,PRISM,20-Jan-2020,NaN,1.734175,0.135881,12.762486,1.0
101005,URGCP,hgnc:30890,URGCP,SKI-II,iuphar.ligand:6041,SKI II,False,False,False,PRISM,20-Jan-2020,NaN,6.688962,0.524111,12.762486,1.0

## EDA drug_is_immunotherapy

Matt wanted to know if there was a relationship between this flag and the interaction_types

In [22]:
df["drug_is_immunotherapy"].value_counts()

drug_is_immunotherapy
False    99657
True      1452
Name: count, dtype: int64

In [23]:
## this looks like more than the "immune"-related interaction_types

df[df["drug_is_immunotherapy"] == True]["interaction_types"].value_counts(dropna=False).sort_index()

interaction_types
activator                    1
agonist                     27
antibody                    78
antibody|immunotherapy       5
binder                       2
blocker                      1
immunotherapy                2
immunotherapy|antibody       3
inhibitor                  109
modulator                    3
NaN                       1221
Name: count, dtype: int64

In [24]:
df[df["drug_is_immunotherapy"] == False]["interaction_types"].value_counts(dropna=False).sort_index()

interaction_types
activator                      616
activator|blocker                2
activator|inhibitor              3
agonist                       5978
agonist|inhibitor               18
agonist|modulator                1
antibody                       269
antisense oligonucleotide        4
binder                         277
blocker                       1848
blocker|activator                4
blocker|inhibitor                5
blocker|modulator                1
cleavage                        85
cleavage|inhibitor               1
immunotherapy                    1
inhibitor                    19653
inhibitor|activator              2
inhibitor|agonist               18
inhibitor|binder                 1
inhibitor|blocker                1
inhibitor|modulator              4
inverse agonist                 37
modulator                     1292
modulator|agonist                3
modulator|inhibitor              4
negative modulator             148
other/unknown                  219
positive modulator            1014
potentiator                     51
vaccine                         40
NaN                          68057
Name: count, dtype: int64

**Summary**

`drug_is_immunotherapy` is basically independent of `interaction_types`:
* `True`: only a small subset have immune-related interaction_type (antibody, immunotherapy)
* `False`: some immune-related interaction_type rows are here! (antibody, immunotherapy, vaccine)

## FILTER, clean Namespaces

In [17]:
## don't include in parser - since don't end up filtering on it

## genes

df["gene_prefix"] = [i.split(":")[0] for i in df["gene_concept_id"]]

df["gene_prefix"].value_counts()

## this is ENSG
df[df["gene_prefix"] == "ensembl"]

gene_prefix
hgnc        101068
ncbigene        38
ensembl          3
Name: count, dtype: int64

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score,gene_prefix
4254,DKFZP434A062,ensembl:ENSG00000262075,DKFZP434A062,lenvatinib,rxcui:1603296,LENVATINIB,True,False,True,PRISM,20-Jan-2020,NaN,1.950947,0.152866,12.762486,1.0,ensembl
16509,TARP,ensembl:ENSG00000289746,TARP,TESTOSTERONE,rxcui:10379,TESTOSTERONE,True,False,False,NCI,14-September-2017,NaN,3.601749,0.094071,12.762486,3.0,ensembl
88657,FLJ42393,ensembl:ENSG00000279891,FLJ42393,amsacrine,rxcui:739,AMSACRINE,True,False,True,PRISM,20-Jan-2020,NaN,1.614577,0.126510,12.762486,1.0,ensembl

In [18]:
## PARTIAL INCLUDE IN PARSER
## drugs

df["drug_prefix"] = [i.split(":")[0] for i in df["drug_concept_id"]]

df["drug_prefix"].value_counts()

drug_prefix
rxcui             38900
chembl            23909
iuphar.ligand     19229
ncit              15576
drugbank           3316
wikidata             96
hemonc               65
drugsatfda.nda       14
chemidplus            4
Name: count, dtype: int64

In [19]:
df[df["drug_prefix"] == "chemidplus"]

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score,gene_prefix,drug_prefix
47159,NOREPINEPHRINE TRANSPORTER,hgnc:11048,SLC6A2,Hypericum,chemidplus:68917-49-7,ST. JOHN'S WORT,False,False,False,TTD,2020.06.01,NaN,0.287256,3.668778,0.078297,1.0,hgnc,chemidplus
82101,NFE2L2,hgnc:7782,NFE2L2,TRIFLOXYSTROBIN,chemidplus:141517-21-7,TRIFLOXYSTROBIN,False,False,False,DTC,2020-09-02,NaN,0.018362,1.222926,0.015015,1.0,hgnc,chemidplus
84531,TP53,hgnc:11998,TP53,TRIFLOXYSTROBIN,chemidplus:141517-21-7,TRIFLOXYSTROBIN,False,False,False,DTC,2020-09-02,NaN,0.033067,1.222926,0.027039,1.0,hgnc,chemidplus
93515,PPARG,hgnc:9236,PPARG,TRIFLOXYSTROBIN,chemidplus:141517-21-7,TRIFLOXYSTROBIN,False,False,False,DTC,2020-09-02,NaN,0.081289,1.222926,0.066471,1.0,hgnc,chemidplus

In [41]:
## EDA of iuphar ligand

df[df["drug_prefix"] == "iuphar.ligand"]

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score,gene_prefix,drug_prefix
30,IUPHAR.RECEPTOR:311,hgnc:4532,HCAR1,IUPHAR.LIGAND:2932,iuphar.ligand:2932,L-LACTIC ACID,False,False,False,GuideToPharmacology,2026.2,agonist,6.688962,3.668778,1.823212,1.0,hgnc,iuphar.ligand
31,IUPHAR.RECEPTOR:311,hgnc:4532,HCAR1,IUPHAR.LIGAND:8467,iuphar.ligand:8467,COMPOUND 2 [PMID: 24486398],False,False,False,GuideToPharmacology,2026.2,agonist,6.688962,3.668778,1.823212,1.0,hgnc,iuphar.ligand
32,IUPHAR.RECEPTOR:311,hgnc:4532,HCAR1,IUPHAR.LIGAND:11197,iuphar.ligand:11197,COMPOUND 2 [PMID: 31932225],False,False,False,GuideToPharmacology,2026.2,agonist,6.688962,3.668778,1.823212,1.0,hgnc,iuphar.ligand
33,IUPHAR.RECEPTOR:311,hgnc:4532,HCAR1,IUPHAR.LIGAND:5783,iuphar.ligand:5783,"3,5-DIHYDROXYBENZOIC ACID",False,False,False,GuideToPharmacology,2026.2,agonist,6.688962,3.668778,1.823212,1.0,hgnc,iuphar.ligand
40,IUPHAR.RECEPTOR:1860,hgnc:9675,PTPRM,IUPHAR.LIGAND:8856,iuphar.ligand:8856,COMPOUND 8A [PMID: 23713581],False,False,False,GuideToPharmacology,2026.2,inhibitor,23.411367,1.834389,12.762486,1.0,hgnc,iuphar.ligand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101081,MTOR,hgnc:3942,MTOR,GOSSYPOL,iuphar.ligand:4204,GOSSYPOL,False,False,False,DTC,2020-09-02,NaN,0.005659,0.087352,0.064784,1.0,hgnc,iuphar.ligand
101082,MTOR,hgnc:3942,MTOR,GR-127935,iuphar.ligand:14,GR 127935,False,False,False,DTC,2020-09-02,NaN,0.008196,0.126510,0.064784,1.0,hgnc,iuphar.ligand
101083,MTOR,hgnc:3942,MTOR,AZD-8055,iuphar.ligand:7714,AZD8055,False,False,True,DTC,2020-09-02,NaN,0.109698,0.282214,0.064784,6.0,hgnc,iuphar.ligand
101095,MTOR,hgnc:3942,MTOR,BIX-01294,iuphar.ligand:7014,BIX-01294,False,False,False,DTC,2020-09-02,NaN,0.014855,0.229299,0.064784,1.0,hgnc,iuphar.ligand
101102,MTOR,hgnc:3942,MTOR,VANOXERINE,iuphar.ligand:9983,VANOXERINE,False,False,False,DTC,2020-09-02,NaN,0.021607,0.333525,0.064784,1.0,hgnc,iuphar.ligand

In [38]:
(19229 + 15576 + 96 + 65 + 14)/ df.shape[0]

0.345963267364923

**[NodeNorm](https://nodenormalization-sri.renci.org/1.5/get_curie_prefixes?semantic_type=biolink%3AChemicalEntity) can't handle:**
* iuphar.ligand
* ncit (for chemicals)
* wikidata
* hemonc
* drugsatfda.nda

Notes:
* assuming chemidplus are equivalent to CAS, based on checking the 2 values.
* assuming chembl = CHEMBL.COMPOUND. based on some spot-checks, it seems to work some of the time?)
* Noticed some names are also not NameRes-able, ex: `COMPOUND 5 [PMID: 29579323]`

In [20]:
## INCLUDE IN PARSER
## NodeNorm doesn't recognize

PREFIXES_TO_DROP = [
    ## . probably will be treated as "all match"...unless escaped
    "ncit",
    "iuphar\\.ligand",
    "wikidata",
    "hemonc",
    "drugsatfda\\.nda",
]

In [21]:
## INCLUDE IN PARSER
## set case=False so it isn't case-sensitive on matches!

n_before = df.shape[0]
df = df[~df.drug_prefix.str.contains('|'.join(PREFIXES_TO_DROP), 
                                     case=False)].copy()

## -> log
print(f"{df.shape[0]} rows ({df.shape[0] / n_before:.1%}) after filtering out drug namespaces that can't be NodeNormed")

66129 rows (65.4%) after filtering out drug namespaces that can't be NodeNormed

In [22]:
df["drug_prefix"].value_counts()

drug_prefix
rxcui         38900
chembl        23909
drugbank       3316
chemidplus        4
Name: count, dtype: int64

In [23]:
## PARTIAL INCLUDE IN PARSER

df.drop(columns=["gene_prefix", "drug_prefix"], inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66129 entries, 0 to 101108
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   gene_claim_name                66122 non-null  object
 1   gene_concept_id                66129 non-null  object
 2   gene_name                      66129 non-null  object
 3   drug_claim_name                66129 non-null  object
 4   drug_concept_id                66129 non-null  object
 5   drug_name                      66129 non-null  object
 6   drug_is_approved               66129 non-null  object
 7   drug_is_immunotherapy          66129 non-null  object
 8   drug_is_antineoplastic         66129 non-null  object
 9   interaction_source_db_name     66129 non-null  object
 10  interaction_source_db_version  66129 non-null  object
 11  interaction_types              15837 non-null  object
 12  interaction_score              66129 non-null  float64
 13  drug_specificity_score         66129 non-null  float64
 14  gene_specificity_score         66129 non-null  float64
 15  evidence_score                 66129 non-null  float64
dtypes: float64(4), object(12)
memory usage: 8.6+ MB

In [25]:
## INCLUDE IN PARSER
## change ID prefixes to Translator standard: mostly making all upper-case

df["drug_concept_id"] = df["drug_concept_id"].str.upper()
df["gene_concept_id"] = df["gene_concept_id"].str.upper()
## special handling for some prefixes: CHEMBL, CHEMIDPLUS -> CAS, NCBIGENE
df["drug_concept_id"] = df["drug_concept_id"].str.replace("CHEMBL:", "CHEMBL.COMPOUND:")
df["drug_concept_id"] = df["drug_concept_id"].str.replace("CHEMIDPLUS:", "CAS:")
df["gene_concept_id"] = df["gene_concept_id"].str.replace("NCBIGENE:", "NCBIGene:")

In [26]:
df[df["drug_concept_id"].str.startswith("CAS")]

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
47159,NOREPINEPHRINE TRANSPORTER,HGNC:11048,SLC6A2,Hypericum,CAS:68917-49-7,ST. JOHN'S WORT,False,False,False,TTD,2020.06.01,NaN,0.287256,3.668778,0.078297,1.0
82101,NFE2L2,HGNC:7782,NFE2L2,TRIFLOXYSTROBIN,CAS:141517-21-7,TRIFLOXYSTROBIN,False,False,False,DTC,2020-09-02,NaN,0.018362,1.222926,0.015015,1.0
84531,TP53,HGNC:11998,TP53,TRIFLOXYSTROBIN,CAS:141517-21-7,TRIFLOXYSTROBIN,False,False,False,DTC,2020-09-02,NaN,0.033067,1.222926,0.027039,1.0
93515,PPARG,HGNC:9236,PPARG,TRIFLOXYSTROBIN,CAS:141517-21-7,TRIFLOXYSTROBIN,False,False,False,DTC,2020-09-02,NaN,0.081289,1.222926,0.066471,1.0

In [30]:
df["interaction_source_db_name"].value_counts().sort_index()

interaction_source_db_name
CGI                                  298
CIViC                                789
CKB-CORE                            1028
COSMIC                                33
CancerCommons                         53
ChEMBL                             11380
ClearityFoundationBiomarkers         105
ClearityFoundationClinicalTrial      115
ClinPGx                             5335
DTC                                19507
DoCM                                  68
Drug Repurposing Hub                8009
FDA                                  402
GuideToPharmacology                 3473
MOAlmanac                            196
MyCancerGenome                       440
MyCancerGenomeClinicalTrial          203
NCI                                 3423
OncoKB                               127
PRISM                               2260
TALC                                 298
TEND                                2148
TTD                                 2955
TdgClinicalTrial                    3484
Name: count, dtype: int64

## Cleaning interaction_types

In [32]:
## INCLUDE IN PARSER

## replace NA with "~NULL"
## makes next steps working with this column easier, will be at end alphanumerically 

df["interaction_types"] = df["interaction_types"].fillna("~NULL")

In [33]:
df["interaction_types"].value_counts().sort_index()

interaction_types
activator                      218
activator|blocker                1
activator|inhibitor              1
agonist                       2275
agonist|inhibitor                7
antibody                        84
antibody|immunotherapy           3
antisense oligonucleotide        2
binder                         276
blocker                       1286
blocker|inhibitor                1
cleavage                        83
cleavage|inhibitor               1
immunotherapy                    2
immunotherapy|antibody           3
inhibitor                     9533
inhibitor|agonist                9
inhibitor|binder                 1
inverse agonist                 33
modulator                      611
negative modulator             144
other/unknown                  184
positive modulator            1005
potentiator                     50
vaccine                         24
~NULL                        50292
Name: count, dtype: int64

### EDA "|-delimited" values

Multiple values, "|"-delimited (special value, needs escaping).

Only a small proportion of the dataset

In [52]:
df_piped_types = df[df["interaction_types"].str.contains("\\|")].copy()

print(f"{df_piped_types.shape[0]} rows with |-delimited interaction_types" + 
      f": {df_piped_types.shape[0] / df.shape[0]:.3%}")

df_piped_types.head()

27 rows with |-delimited interaction_types: 0.041%

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
1165,IUPHAR.RECEPTOR:627,HGNC:8910,PGR,IUPHAR.LIGAND:2805,RXCUI:6964,MIFEPRISTONE,True,False,False,GuideToPharmacology,2026.2,inhibitor|agonist,0.093946,0.131028,0.143399,5.0
1174,IUPHAR.RECEPTOR:627,HGNC:8910,PGR,IUPHAR.LIGAND:7460,RXCUI:1005920,ULIPRISTAL ACETATE,True,False,False,GuideToPharmacology,2026.2,agonist|inhibitor,3.156589,3.668778,0.143399,6.0
12107,ADRB2,HGNC:286,ADRB2,DILEVALOL HYDROCHLORIDE,CHEMBL.COMPOUND:CHEMBL1204165,DILEVALOL HYDROCHLORIDE,True,False,False,ChEMBL,37,agonist|inhibitor,0.070623,1.222926,0.057749,1.0
22474,BRAF,HGNC:1097,BRAF,VEMURAFENIB,RXCUI:1147220,VEMURAFENIB,True,False,True,MyCancerGenomeClinicalTrial,30-Feburary-2014,activator|inhibitor,1.114827,0.087352,0.050049,255.0
24897,IUPHAR.RECEPTOR:25,HGNC:281,ADRA2A,IUPHAR.LIGAND:502,RXCUI:8153,PHENTOLAMINE,True,False,False,GuideToPharmacology,2026.2,agonist|inhibitor,0.206723,0.407642,0.084520,6.0

### Split "|-delimited"

In [34]:
## INCLUDE IN PARSER

df["interaction_types"] = df["interaction_types"].str.split("|")

In [54]:
## EDA only
## this is correct - the row count in df_piped_types was the same
df[df["interaction_types"].map(len) > 1].shape[0]

df[df["interaction_types"].map(len) > 1]

27

,gene_claim_name,gene_concept_id,gene_name,drug_claim_name,drug_concept_id,drug_name,drug_is_approved,drug_is_immunotherapy,drug_is_antineoplastic,interaction_source_db_name,interaction_source_db_version,interaction_types,interaction_score,drug_specificity_score,gene_specificity_score,evidence_score
1165,IUPHAR.RECEPTOR:627,HGNC:8910,PGR,IUPHAR.LIGAND:2805,RXCUI:6964,MIFEPRISTONE,True,False,False,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.093946,0.131028,0.143399,5.0
1174,IUPHAR.RECEPTOR:627,HGNC:8910,PGR,IUPHAR.LIGAND:7460,RXCUI:1005920,ULIPRISTAL ACETATE,True,False,False,GuideToPharmacology,2026.2,"[agonist, inhibitor]",3.156589,3.668778,0.143399,6.0
12107,ADRB2,HGNC:286,ADRB2,DILEVALOL HYDROCHLORIDE,CHEMBL.COMPOUND:CHEMBL1204165,DILEVALOL HYDROCHLORIDE,True,False,False,ChEMBL,37,"[agonist, inhibitor]",0.070623,1.222926,0.057749,1.0
22474,BRAF,HGNC:1097,BRAF,VEMURAFENIB,RXCUI:1147220,VEMURAFENIB,True,False,True,MyCancerGenomeClinicalTrial,30-Feburary-2014,"[activator, inhibitor]",1.114827,0.087352,0.050049,255.0
24897,IUPHAR.RECEPTOR:25,HGNC:281,ADRA2A,IUPHAR.LIGAND:502,RXCUI:8153,PHENTOLAMINE,True,False,False,GuideToPharmacology,2026.2,"[agonist, inhibitor]",0.206723,0.407642,0.084520,6.0
25250,IUPHAR.RECEPTOR:496,HGNC:17993,TRPM4,IUPHAR.LIGAND:1713,RXCUI:318,ADENOSINE TRIPHOSPHATE,True,False,False,GuideToPharmacology,2026.2,"[blocker, inhibitor]",0.162016,0.215810,0.750734,1.0
25973,IUPHAR.RECEPTOR:621,HGNC:3468,ESR2,IUPHAR.LIGAND:1016,RXCUI:10324,TAMOXIFEN,True,False,True,GuideToPharmacology,2026.2,"[agonist, inhibitor]",0.078142,0.065514,0.119276,10.0
26549,IL6,HGNC:6018,IL6,ZILTIVEKIMAB,CHEMBL.COMPOUND:CHEMBL4297732,ZILTIVEKIMAB,False,False,False,ChEMBL,37,"[inhibitor, binder]",0.650316,3.668778,0.177257,1.0
27327,PDCD1,HGNC:8760,PDCD1,NIVOLUMAB,RXCUI:1597876,NIVOLUMAB,True,True,True,MyCancerGenome,20-Jun-2017,"[immunotherapy, antibody]",0.148442,0.114649,0.184964,7.0
27328,PDCD1,HGNC:8760,PDCD1,AMP-224,DRUGBANK:DB15767,AMP-224,False,True,True,MyCancerGenome,20-Jun-2017,"[antibody, immunotherapy]",1.357181,3.668778,0.184964,2.0
27330,PDCD1,HGNC:8760,PDCD1,MK-3475,RXCUI:1547545,PEMBROLIZUMAB,True,True,True,MyCancerGenome,20-Jun-2017,"[immunotherapy, antibody]",0.066204,0.089482,0.184964,4.0
28887,IUPHAR.RECEPTOR:34,HGNC:336,AGTR1,IUPHAR.LIGAND:6902,DRUGBANK:DB12199,TRV-120027,False,False,False,GuideToPharmacology,2026.2,"[inhibitor, agonist]",1.672241,3.668778,0.151934,3.0
35482,IUPHAR.RECEPTOR:6,HGNC:5293,HTR2A,IUPHAR.LIGAND:50,RXCUI:221153,QUETIAPINE FUMARATE,True,False,False,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.014669,0.076433,0.047979,4.0
35526,IUPHAR.RECEPTOR:6,HGNC:5293,HTR2A,IUPHAR.LIGAND:91,RXCUI:8332,PINDOLOL,True,False,False,GuideToPharmacology,2026.2,"[agonist, inhibitor]",0.027081,0.282214,0.047979,2.0
38678,IUPHAR.RECEPTOR:28,HGNC:285,ADRB1,IUPHAR.LIGAND:91,RXCUI:8332,PINDOLOL,True,False,False,GuideToPharmacology,2026.2,"[agonist, inhibitor]",0.196459,0.282214,0.077348,9.0
39837,IUPHAR.RECEPTOR:620,HGNC:3467,ESR1,IUPHAR.LIGAND:1016,RXCUI:10324,TAMOXIFEN,True,False,True,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.052450,0.065514,0.047094,17.0
39843,IUPHAR.RECEPTOR:620,HGNC:3467,ESR1,IUPHAR.LIGAND:2820,RXCUI:166551,RALOXIFENE HYDROCHLORIDE,True,False,False,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.044429,0.104822,0.047094,9.0
40177,IUPHAR.RECEPTOR:325,HGNC:8542,P2RY4,IUPHAR.LIGAND:1713,RXCUI:318,ADENOSINE TRIPHOSPHATE,True,False,False,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.172142,0.215810,0.797655,1.0
47989,IUPHAR.RECEPTOR:599,HGNC:10259,RORB,IUPHAR.LIGAND:2644,RXCUI:10753,TRETINOIN,True,False,True,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.205814,0.040316,2.552497,2.0
48011,ESR1,HGNC:3467,ESR1,FULVESTRANT,RXCUI:282357,FULVESTRANT,True,False,True,ChEMBL,37,"[cleavage, inhibitor]",0.159487,0.141107,0.047094,24.0
50747,CD274,HGNC:17635,CD274,MPDL3280A,RXCUI:1792776,ATEZOLIZUMAB,True,True,True,MyCancerGenome,20-Jun-2017,"[antibody, immunotherapy]",0.658049,0.146751,0.344932,13.0
63406,IUPHAR.RECEPTOR:323,HGNC:8539,P2RY1,IUPHAR.LIGAND:1713,RXCUI:318,ADENOSINE TRIPHOSPHATE,True,False,False,GuideToPharmacology,2026.2,"[agonist, inhibitor]",0.081008,0.215810,0.375367,1.0
74559,IUPHAR.RECEPTOR:29,HGNC:286,ADRB2,IUPHAR.LIGAND:91,RXCUI:8332,PINDOLOL,True,False,False,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.130380,0.282214,0.057749,8.0
78131,IUPHAR.RECEPTOR:700,HGNC:2026,CLCNKA,IUPHAR.LIGAND:2439,RXCUI:7418,NIFLUMIC ACID,False,False,False,GuideToPharmacology,2026.2,"[activator, blocker]",2.401166,0.282214,4.254162,2.0
87533,IUPHAR.RECEPTOR:7,HGNC:5294,HTR2B,IUPHAR.LIGAND:91,RXCUI:8332,PINDOLOL,True,False,False,GuideToPharmacology,2026.2,"[inhibitor, agonist]",0.052967,0.282214,0.093842,2.0
96808,CTLA4,HGNC:2505,CTLA4,IPILIMUMAB,RXCUI:1094833,IPILIMUMAB,True,True,True,MyCancerGenome,20-Jun-2017,"[immunotherapy, antibody]",0.495479,0.174704,0.354514,8.0
96809,CTLA4,HGNC:2505,CTLA4,TREMELIMUMAB,RXCUI:2619313,TREMELIMUMAB,True,True,True,MyCancerGenome,20-Jun-2017,"[antibody, immunotherapy]",1.114827,0.524111,0.354514,6.0

Then expand to multiple rows using pandas explode

In [35]:
## INCLUDE IN PARSER

df = df.explode("interaction_types", ignore_index=True)

## -> log
print(f"{df.shape[0]} rows after expanding rows with multiple interaction_type values")

66156 rows after expanding rows with multiple interaction_type values

## EDA Merging by gene-drug pairs

In [ ]:
## first drop some columns - not needed OR values won't make sense after merge
## makes merge faster

# cols_not_needed = [
#     "gene_claim_name", 
#     "drug_claim_name",
#     "interaction_source_db_version", 
#     "gene_prefix",
#     "drug_prefix",
# ]

# merge1 = df.drop(columns=cols_not_needed).copy()

In [ ]:
## merge: takes ~10s to run

# cols_define_1 = ["gene_concept_id", "drug_concept_id"]

# merge1 = merge1.groupby(by=cols_define_1).agg(set).reset_index().copy()

In [ ]:
# merge1.shape[0]

# merge1

In [ ]:
## all single values - so same for a gene-drug pair

# ## tied to gene
# merge1[merge1["gene_name"].map(len) > 1].shape[0]

# ## tied to drug, basically a node attribute/annotation
# merge1[merge1["drug_name"].map(len) > 1].shape[0]
# merge1[merge1["drug_is_approved"].map(len) > 1].shape[0]
# merge1[merge1["drug_is_immunotherapy"].map(len) > 1].shape[0]
# merge1[merge1["drug_is_antineoplastic"].map(len) > 1].shape[0]

In [ ]:
## all single values - so same for a gene-drug pair

# ## scores for gene-drug pair
# merge1[merge1["interaction_score"].map(len) > 1].shape[0]
# merge1[merge1["evidence_score"].map(len) > 1].shape[0]

# ## scores for only drug or only gene
# merge1[merge1["drug_specificity_score"].map(len) > 1].shape[0]
# merge1[merge1["gene_specificity_score"].map(len) > 1].shape[0]

In [ ]:
## end up with multiple values 

# merge1[merge1["interaction_types"].map(len) > 1].shape[0]

# merge1[merge1["interaction_source_db_name"].map(len) > 1].shape[0]

### interaction_types

**6.7%** of the dataset has **multiple interaction_types from the merge**. 

Are there sets that don't make sense?

In [ ]:
# merge1_multi_types = merge1[merge1["interaction_types"].map(len) > 1].copy()

# print(f"{merge1_multi_types.shape[0] / merge1.shape[0]:.2%}")

# merge1_multi_types

In [ ]:
# SORT values first - so the sets are ideally unique beforehand

# merge1_multi_types["interaction_types"] = [",".join(sorted(i)) for i in merge1_multi_types["interaction_types"]]

In [ ]:
# merge1_multi_types["interaction_types"].nunique()

In [ ]:
# merge1_multi_types["interaction_types"].value_counts(normalize=True)

Top are (cover >82%):
* `inhibitor,~NULL` (60%)
* `agonist,~NULL` (>14%)
* `positive modulator,~NULL` (>8%)

In [ ]:
# merge1_multi_types["interaction_types"].value_counts().sort_index()

**MERGED DATA ISSUES**

(fully reviewed)

**Opposing**
* **agonist,inhibitor**

**Makes sense, but tricky to merge? (1 example of each kind)**
* activator,potentiator,~NULL
* **agonist,antibody**
* antibody,binder,~NULL
* antibody,blocker,immunotherapy,inhibitor,~NULL
* antibody,inhibitor
* blocker,inhibitor
* **cleavage,inhibitor,~NULL**
* inhibitor,inverse agonist,~NULL

In [ ]:
# merge1_multi_types[merge1_multi_types["interaction_types"] == "agonist,antibody"]

In [ ]:
rows_with_plain = merge1_multi_types[merge1_multi_types["interaction_types"].str.contains("NULL|other")].copy()


print(f"{rows_with_plain.shape[0] / merge1_multi_types.shape[0]:.2%}")

### interaction_source_db_name

**10.8%** of data has multiple sources after merge

EDA only

In [ ]:
# merge1_multi_sources = merge1[merge1["interaction_source_db_name"].map(len) > 1].copy()

# print(f"{merge1_multi_sources.shape[0] / merge1.shape[0]:.2%}")

# merge1_multi_sources

In [ ]:
# SORT values first - so the sets are ideally unique beforehand

# merge1_multi_sources["interaction_source_db_name"] = [",".join(sorted(i)) for i in merge1_multi_sources["interaction_source_db_name"]]

In [ ]:
# merge1_multi_sources["interaction_source_db_name"].nunique()

In [ ]:
# merge1_multi_sources["interaction_source_db_name"].value_counts()[0:10]

## EDA Merging by gene-drug-interaction_type combos

In [ ]:
# ## first drop some columns - not needed OR values won't make sense after merge
# ## makes merge faster

# ## and order for readability
# merge2 = df[["drug_concept_id", "drug_name", 
#              "gene_concept_id", "gene_name",
#              "interaction_types", "interaction_source_db_name",
#              "interaction_score", "evidence_score"
#             ]].copy()

In [ ]:
# ## merge: takes ~5s to run

# cols_define_edge_2 = ["gene_concept_id", "drug_concept_id", "interaction_types"]

# merge2 = merge2.groupby(by=cols_define_edge_2).agg(set).reset_index().copy()

In [ ]:
# merge2.shape[0]

# merge2

In [ ]:
# ## how many rows with "duplicate" drug-gene pairs

# merge2_samepair = merge2[merge2.duplicated(subset=["gene_concept_id", "drug_concept_id"], keep=False)].copy()

# merge2_samepair.shape[0]

In [ ]:
# merge2_samepair[40:61]

Based on spot-check, don't see cases where the `~NULL` has the same sources as its "dup" row...

`[44:47]` is a set of 3

`.loc[56285:56287]` is a set of 3 with other/unknown and NULL

In [ ]:
# ## looking for "other/unknown stuff"
# merge2_samepair[merge2_samepair["interaction_types"].str.contains("other")]

In [ ]:
# merge2_samepair.loc[56285:56287]

## Merge by drug-gene-mod_type combos

In [56]:
df.columns.to_list()

['gene_claim_name',
 'gene_concept_id',
 'gene_name',
 'drug_claim_name',
 'drug_concept_id',
 'drug_name',
 'drug_is_approved',
 'drug_is_immunotherapy',
 'drug_is_antineoplastic',
 'interaction_source_db_name',
 'interaction_source_db_version',
 'interaction_types',
 'interaction_score',
 'drug_specificity_score',
 'gene_specificity_score',
 'evidence_score']

In [36]:
## PARTIAL INCLUDE IN PARSER (config yaml)

## only including necessary columns 
##   + drug/gene names for readability/comparison with website
## dropping columns makes merge faster

## order for readability
experiment_setup = df[["drug_concept_id", "drug_name", 
                       "gene_concept_id", "gene_name",
                       "interaction_types", "interaction_source_db_name",
                       "interaction_score", "evidence_score"
                      ]].copy()

**FIRST map interaction_types for "plain interacts_with" to 1 term -> "~PLAIN_INTERACTS"**

**Make new column and use it going forward - mod_type** (but in notebook, keep original so can check):
* If "other/unknown" or `~NULL`, put `~PLAIN_INTERACTS`
* Else keep original value

Reasoning:
* then when they both occur for same drug-gene pair, their rows can be merged
  * All other interaction_types map to diff predicate/qualifier-sets so they don't need merging later (confirmed 11/18 night)
* makes following logic easier: detecting "only one edge" or "plain interacts_with edge"
* Other option is to map everything to predicate/qualifier-sets, then do logic with predicate/qualifier-sets. But I think that's more complicated to check…

In [37]:
## INCLUDE IN PARSER

plain_interact_types = {"other/unknown", "~NULL"}

experiment_setup["mod_type"] = ["~PLAIN_INTERACTS" if i in plain_interact_types else i for i in experiment_setup["interaction_types"]]

In [59]:
## EDA: check how it looks

## regular: don't use "other" because "immunOTHERapy"
experiment_setup[experiment_setup["interaction_types"].str.contains("unknown|NULL")].shape[0]

## modded
experiment_setup[experiment_setup["mod_type"] == "~PLAIN_INTERACTS"].shape[0]

50476

50476

In [60]:
## more checks how it looks
experiment_setup[experiment_setup["mod_type"] == "~PLAIN_INTERACTS"]["interaction_types"].unique()

experiment_setup[~ (experiment_setup["mod_type"] == "~PLAIN_INTERACTS")]["interaction_types"].unique()

array(['~NULL', 'other/unknown'], dtype=object)

array(['inhibitor', 'agonist', 'blocker', 'positive modulator',
       'antibody', 'binder', 'modulator', 'potentiator', 'cleavage',
       'negative modulator', 'activator', 'inverse agonist', 'vaccine',
       'immunotherapy', 'antisense oligonucleotide'], dtype=object)

In [38]:
## INCLUDE IN PARSER

## group by drug ID, gene ID, mod_type combo

## saving in diff variable in case I want to still work with no-grouping-done later
# experiment_mergeMain = experiment_setup.copy()

## merge: takes ~3s to run
cols_define_edge_3 = ["drug_concept_id", "gene_concept_id", "mod_type"]

## when it can be multiple values, run set
## otherwise, the value is always the same (from EDA), so just keep the first
experiment_setup = experiment_setup.groupby(by=cols_define_edge_3).agg(
    {
        "interaction_types": set, 
        "interaction_source_db_name": set,
        "interaction_score": 'first',
        "evidence_score": 'first',
        "drug_name": 'first',
        "gene_name": 'first',

    }
).reset_index().copy()

In [62]:
## log

experiment_setup.shape[0]

56429

In [63]:
## EDA

## check what rows look like with both original ~PLAIN_INTERACTS values

experiment_setup[experiment_setup["gene_concept_id"] == "HGNC:9565"]

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,interaction_score,evidence_score,drug_name,gene_name
8585,CHEMBL.COMPOUND:CHEMBL2103884,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},0.176025,1.0,OPROZOMIB,PSMD7
13869,CHEMBL.COMPOUND:CHEMBL3545432,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},0.176025,1.0,IXAZOMIB CITRATE,PSMD7
19886,CHEMBL.COMPOUND:CHEMBL5315122,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},0.176025,1.0,BORTEZOMIB D-MANNITOL,PSMD7
30771,RXCUI:1302966,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},0.424696,4.0,CARFILZOMIB,PSMD7
30772,RXCUI:1302966,HGNC:9565,~PLAIN_INTERACTS,"{other/unknown, ~NULL}","{MyCancerGenome, DTC}",0.424696,4.0,CARFILZOMIB,PSMD7
35077,RXCUI:1723735,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},0.155557,1.0,IXAZOMIB,PSMD7
46213,RXCUI:358258,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},0.300628,4.0,BORTEZOMIB,PSMD7
46214,RXCUI:358258,HGNC:9565,~PLAIN_INTERACTS,"{other/unknown, ~NULL}","{MyCancerGenome, DTC}",0.300628,4.0,BORTEZOMIB,PSMD7

In [64]:
experiment_setup[experiment_setup["mod_type"] == "~PLAIN_INTERACTS"].shape[0]

42122

## Special logic

### sources

Create a mapping df: group-by "drug-gene" pair -> get a set of all sources. 

Then make a new sources column **mod_sources** (but in notebook, keep original so can check):
* If "~PLAIN_INTERACTS": use the mapping df's value for drug-gene pair (all sources)
* Else: keep original value

In [39]:
## INCLUDE IN PARSER

experiment_sources = experiment_setup.copy()

drug_gene_pair = ["drug_concept_id", "gene_concept_id"]

In [40]:
## INCLUDE IN PARSER

## need to merge sets!
## and keep multi-index, annoying but seems easier to retrieve values later
experiment_sources = experiment_sources.groupby(by=drug_gene_pair).agg(
    {"interaction_source_db_name":lambda x: set.union(*x)})

In [67]:
experiment_sources

                                                                                                  interaction_source_db_name
drug_concept_id            gene_concept_id
CAS:141517-21-7            HGNC:11998                                                                                  {DTC}
                           HGNC:7782                                                                                   {DTC}
                           HGNC:9236                                                                                   {DTC}
CAS:68917-49-7             HGNC:11048                                                                                  {TTD}
CHEMBL.COMPOUND:CHEMBL1010 HGNC:14129                                                                                  {DTC}
...                                                                                                                      ...
RXCUI:9997                 HGNC:7876                                                                               {ClinPGx}
                           HGNC:7978                                                                  {Drug Repurposing Hub}
                           HGNC:7979        {TEND, TdgClinicalTrial, Drug Repurposing Hub, ChEMBL, GuideToPharmacology, TTD}
                           HGNC:8910                                                                  {Drug Repurposing Hub}
                           HGNC:9236                                                                                   {DTC}

[51874 rows x 1 columns]

In [68]:
## trying out how to get specific value in this df using multi-index
## loc returns a series, turn to list and get first/only item

experiment_sources.loc["RXCUI:1302966", "HGNC:9565"]

experiment_sources.loc["RXCUI:1302966", "HGNC:9565"].to_list()[0]

interaction_source_db_name    {MyCancerGenome, ChEMBL, DTC}
Name: (RXCUI:1302966, HGNC:9565), dtype: object

{'ChEMBL', 'DTC', 'MyCancerGenome'}

In [41]:
## add new column to experiment df
## in specific spot

mod_sources = [
    experiment_sources.loc[x.drug_concept_id, x.gene_concept_id].to_list()[0] if x.mod_type == "~PLAIN_INTERACTS"
    else x.interaction_source_db_name
    for x in experiment_setup[["drug_concept_id", "gene_concept_id", "mod_type", "interaction_source_db_name"]].itertuples()
]

experiment_setup.insert(5, "mod_sources", mod_sources)

In [70]:
## check what rows look like with original ~PLAIN_INTERACTS values

experiment_setup[experiment_setup["gene_concept_id"] == "HGNC:9565"]

experiment_setup[experiment_setup.duplicated(subset=["drug_concept_id", "gene_concept_id"], keep=False)][60:70]

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
8585,CHEMBL.COMPOUND:CHEMBL2103884,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.176025,1.0,OPROZOMIB,PSMD7
13869,CHEMBL.COMPOUND:CHEMBL3545432,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.176025,1.0,IXAZOMIB CITRATE,PSMD7
19886,CHEMBL.COMPOUND:CHEMBL5315122,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.176025,1.0,BORTEZOMIB D-MANNITOL,PSMD7
30771,RXCUI:1302966,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.424696,4.0,CARFILZOMIB,PSMD7
30772,RXCUI:1302966,HGNC:9565,~PLAIN_INTERACTS,"{other/unknown, ~NULL}","{MyCancerGenome, DTC}","{MyCancerGenome, ChEMBL, DTC}",0.424696,4.0,CARFILZOMIB,PSMD7
35077,RXCUI:1723735,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.155557,1.0,IXAZOMIB,PSMD7
46213,RXCUI:358258,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.300628,4.0,BORTEZOMIB,PSMD7
46214,RXCUI:358258,HGNC:9565,~PLAIN_INTERACTS,"{other/unknown, ~NULL}","{MyCancerGenome, DTC}","{MyCancerGenome, ChEMBL, DTC}",0.300628,4.0,BORTEZOMIB,PSMD7

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
5827,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3236,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.035580,3.0,TAK-285,EGFR
5828,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3236,~PLAIN_INTERACTS,{~NULL},"{PRISM, Drug Repurposing Hub}","{PRISM, ChEMBL, Drug Repurposing Hub}",0.035580,3.0,TAK-285,EGFR
5829,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3430,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.056549,3.0,TAK-285,ERBB2
5830,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3430,~PLAIN_INTERACTS,{~NULL},"{Drug Repurposing Hub, TTD}","{ChEMBL, Drug Repurposing Hub, TTD}",0.056549,3.0,TAK-285,ERBB2
5866,CHEMBL.COMPOUND:CHEMBL1628227,HGNC:5182,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.635603,3.0,DOXEPIN,HRH1
5867,CHEMBL.COMPOUND:CHEMBL1628227,HGNC:5182,~PLAIN_INTERACTS,{~NULL},{DTC},"{ChEMBL, DTC}",0.635603,3.0,DOXEPIN,HRH1
5886,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5286,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.111483,2.0,GSK163090,HTR1A
5887,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5286,~PLAIN_INTERACTS,{~NULL},{Drug Repurposing Hub},"{ChEMBL, Drug Repurposing Hub}",0.111483,2.0,GSK163090,HTR1A
5888,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5287,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.187291,2.0,GSK163090,HTR1B
5889,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5287,~PLAIN_INTERACTS,{~NULL},{Drug Repurposing Hub},"{ChEMBL, Drug Repurposing Hub}",0.187291,2.0,GSK163090,HTR1B

### scores logic

~In notebook, creating new df rather than working on old to make easier to adjust~

Only care about logic for removing scores (setting NA)

Group by "drug-gene" pair:
* If there's > 1 row (mod_type): 
  * If row mod_type isn't "~PLAIN_INTERACTS": remove scores

In [46]:
# experiment_scores = experiment_mergeMain.copy()

# drug_gene_pair = ["drug_concept_id", "gene_concept_id"]

In [42]:
## iterate through a group-by, takes ~5s

grp = experiment_setup.groupby(by=drug_gene_pair)

for name, group in grp:
    if group.shape[0] > 1:
        for idx,row in group.iterrows():
            if row.mod_type != "~PLAIN_INTERACTS":
                experiment_setup.at[idx, "interaction_score"] = pd.NA
                experiment_setup.at[idx, "evidence_score"] = pd.NA

In [43]:
## check what rows look like
## can also look at how many rows have scores (grep matches this count)


experiment_setup.info()

print("\n")
print(experiment_setup["interaction_score"].isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56429 entries, 0 to 56428
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   drug_concept_id             56429 non-null  object
 1   gene_concept_id             56429 non-null  object
 2   mod_type                    56429 non-null  object
 3   interaction_types           56429 non-null  object
 4   interaction_source_db_name  56429 non-null  object
 5   mod_sources                 56429 non-null  object
 6   interaction_score           51842 non-null  float64
 7   evidence_score              51842 non-null  float64
 8   drug_name                   56429 non-null  object
 9   gene_name                   56429 non-null  object
dtypes: float64(2), object(8)
memory usage: 4.3+ MB


4587

In [73]:
## check what rows look like

experiment_setup[experiment_setup["gene_concept_id"] == "HGNC:9565"]

experiment_setup[experiment_setup.duplicated(subset=drug_gene_pair, keep=False)][60:70]

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
8585,CHEMBL.COMPOUND:CHEMBL2103884,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.176025,1.0,OPROZOMIB,PSMD7
13869,CHEMBL.COMPOUND:CHEMBL3545432,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.176025,1.0,IXAZOMIB CITRATE,PSMD7
19886,CHEMBL.COMPOUND:CHEMBL5315122,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.176025,1.0,BORTEZOMIB D-MANNITOL,PSMD7
30771,RXCUI:1302966,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,CARFILZOMIB,PSMD7
30772,RXCUI:1302966,HGNC:9565,~PLAIN_INTERACTS,"{other/unknown, ~NULL}","{MyCancerGenome, DTC}","{MyCancerGenome, ChEMBL, DTC}",0.424696,4.0,CARFILZOMIB,PSMD7
35077,RXCUI:1723735,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.155557,1.0,IXAZOMIB,PSMD7
46213,RXCUI:358258,HGNC:9565,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,BORTEZOMIB,PSMD7
46214,RXCUI:358258,HGNC:9565,~PLAIN_INTERACTS,"{other/unknown, ~NULL}","{MyCancerGenome, DTC}","{MyCancerGenome, ChEMBL, DTC}",0.300628,4.0,BORTEZOMIB,PSMD7

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
5827,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3236,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,TAK-285,EGFR
5828,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3236,~PLAIN_INTERACTS,{~NULL},"{PRISM, Drug Repurposing Hub}","{PRISM, ChEMBL, Drug Repurposing Hub}",0.035580,3.0,TAK-285,EGFR
5829,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3430,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,TAK-285,ERBB2
5830,CHEMBL.COMPOUND:CHEMBL1614725,HGNC:3430,~PLAIN_INTERACTS,{~NULL},"{Drug Repurposing Hub, TTD}","{ChEMBL, Drug Repurposing Hub, TTD}",0.056549,3.0,TAK-285,ERBB2
5866,CHEMBL.COMPOUND:CHEMBL1628227,HGNC:5182,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,DOXEPIN,HRH1
5867,CHEMBL.COMPOUND:CHEMBL1628227,HGNC:5182,~PLAIN_INTERACTS,{~NULL},{DTC},"{ChEMBL, DTC}",0.635603,3.0,DOXEPIN,HRH1
5886,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5286,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,GSK163090,HTR1A
5887,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5286,~PLAIN_INTERACTS,{~NULL},{Drug Repurposing Hub},"{ChEMBL, Drug Repurposing Hub}",0.111483,2.0,GSK163090,HTR1A
5888,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5287,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,GSK163090,HTR1B
5889,CHEMBL.COMPOUND:CHEMBL1631540,HGNC:5287,~PLAIN_INTERACTS,{~NULL},{Drug Repurposing Hub},"{ChEMBL, Drug Repurposing Hub}",0.187291,2.0,GSK163090,HTR1B

## For comparing to pipeline output

In [44]:
## extra edges

augmented = ["agonist", "antibody", "blocker", "inhibitor", "inverse agonist"]

## extra edge count
extra_count = experiment_setup[experiment_setup.mod_type.str.contains('|'.join(augmented), case=False)].shape[0]
extra_count

## count of binder edges: same dp_interacts predicate
binder_count = experiment_setup[experiment_setup["mod_type"] == "binder"].shape[0]
binder_count

## count of dp_interacts edges
extra_count + binder_count

## total edges
experiment_setup.shape[0] + extra_count

11900

277

12177

68329

In [48]:
supporting_data_sources = {    ## become a RetrievalSource object in sources property
  ## key: most of the values from data's interaction_source_db_name column
  ## value: infores ID. sometimes same letters as key, sometimes NOT
  "CGI": "infores:cgi",
  "CIViC": "infores:civic",
  "CKB-CORE": "infores:ckb-core",
  "COSMIC": "infores:cosmic",
  "CancerCommons": "infores:cancercommons",
  "ChEMBL": "infores:chembl",
  "ClearityFoundationBiomarkers": "infores:clearity-biomarkers",
  "ClearityFoundationClinicalTrial": "infores:clearity-clinical-trial",
  "ClinPGx": "infores:clinpgx",
  "DTC": "infores:dtc",
  "DoCM": "infores:docm",
  "Drug Repurposing Hub": "infores:drug-repurposing-hub",
  "FDA": "infores:fda-pgx",
  "GuideToPharmacology": "infores:gtopdb",
  "MOAlmanac": "infores:moalmanac",
  "MyCancerGenome": "infores:mycancergenome",
  "MyCancerGenomeClinicalTrial": "infores:mycancergenome-trials",
  "NCI": "infores:ncit",
  "OncoKB": "infores:oncokb",
  "TTD": "infores:ttd",
}

publications = {     ## become an element in "publications" list
  ## key: a few values from data's interaction_source_db_name column
  ## value: corresponding publication that dgidb used
  ## from citation info in https://dgidb.org/browse/sources
  "TALC": "PMID:25535693",
  "TEND": "PMID:21804595",
  "TdgClinicalTrial": "PMID:24016212",
  "PRISM": "PMID:32613204",
}

In [88]:
if not list(set(df["interaction_source_db_name"].unique()) - supporting_data_sources.keys() - publications.keys()):
    print("yay")

yay

In [43]:
experiment_setup[experiment_setup["drug_concept_id"] == "CHEMBL.COMPOUND:CHEMBL101168"]

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
0,CHEMBL.COMPOUND:CHEMBL101168,HGNC:2596,~PLAIN_INTERACTS,{~NULL},{DTC},{DTC},0.044017,1.0,CHEMBL:CHEMBL101168,CYP1A2
1,CHEMBL.COMPOUND:CHEMBL101168,HGNC:2637,~PLAIN_INTERACTS,{~NULL},{DTC},{DTC},0.029197,1.0,CHEMBL:CHEMBL101168,CYP3A4

In [44]:
experiment_setup.head()

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
0,CHEMBL.COMPOUND:CHEMBL101168,HGNC:2596,~PLAIN_INTERACTS,{~NULL},{DTC},{DTC},0.044017,1.0,CHEMBL:CHEMBL101168,CYP1A2
1,CHEMBL.COMPOUND:CHEMBL101168,HGNC:2637,~PLAIN_INTERACTS,{~NULL},{DTC},{DTC},0.029197,1.0,CHEMBL:CHEMBL101168,CYP3A4
2,CHEMBL.COMPOUND:CHEMBL10118,HGNC:30863,~PLAIN_INTERACTS,{~NULL},{DTC},{DTC},104.407597,2.0,FAMOXADONE,UQCR10
3,CHEMBL.COMPOUND:CHEMBL101510,HGNC:2625,~PLAIN_INTERACTS,{~NULL},{DTC},{DTC},0.087885,1.0,CHEMBL:CHEMBL101510,CYP2D6
4,CHEMBL.COMPOUND:CHEMBL101804,HGNC:12841,~PLAIN_INTERACTS,{~NULL},{DTC},{DTC},0.250980,1.0,CHEMBL:CHEMBL101804,YES1

In [45]:
experiment_setup[(experiment_setup["mod_sources"].map(len) > 1)].shape[0]

7604

Grep: `grep -c -E "(supporting_data_source.*){2}" dgidb_edges.jsonl`

Ref: https://unix.stackexchange.com/a/596143

In [49]:

## number of rows with multiple final supporting sources
## same as pipeline before normalization! (grep)

n_final_multi = 0

for row in experiment_setup[["mod_sources", "mod_type"]].itertuples():
    temp = 0
    for i in row.mod_sources:
        if i not in publications.keys():
            temp += 1
    if temp > 1:
        n_final_multi += 1
        if row.mod_type in augmented:
            n_final_multi += 1
        
print(n_final_multi)

6901

In [50]:
## number of rows with publications
## same as pipeline before normalization! (grep)

n_final_pubs = 0

for row in experiment_setup[["mod_sources", "mod_type"]].itertuples():
    has_pub = False
    
    for i in row.mod_sources:
        if i in publications.keys():
            has_pub = True
    if has_pub:
        n_final_pubs += 1
        if row.mod_type in augmented:
            n_final_pubs += 1

print(n_final_pubs)

6433

In [67]:
experiment_setup["mod_type"].value_counts()

mod_type
~PLAIN_INTERACTS             33563
inhibitor                     6627
agonist                       1865
blocker                       1101
positive modulator             891
modulator                      299
activator                      188
binder                         161
antibody                        82
negative modulator              79
cleavage                        75
potentiator                     42
inverse agonist                 29
immunotherapy                    8
vaccine                          3
antisense oligonucleotide        2
Name: count, dtype: int64

In [60]:
experiment_setup.columns

Index(['drug_concept_id', 'gene_concept_id', 'mod_type', 'interaction_types',
       'interaction_source_db_name', 'mod_sources', 'interaction_score',
       'evidence_score', 'drug_name', 'gene_name'],
      dtype='object')

In [63]:
## parser overwrites interaction_source_db_name, doesn't have mod_sources

# experiment_setup[(experiment_setup["mod_type"] == "~PLAIN_INTERACTS") &
#                  ((experiment_setup["mod_sources"].map(len) > 1))].drop(columns=["interaction_source_db_name",
#                                                                                  "drug_name",
#                                                                                 "gene_name"])

# experiment_setup[(experiment_setup["mod_type"] == "binder") &
#                  (experiment_setup["interaction_score"].isna())].drop(columns=["interaction_source_db_name",
#                                                                                  "drug_name",
#                                                                                 "gene_name"]).head()

,drug_concept_id,gene_concept_id,mod_type,interaction_types,mod_sources,interaction_score,evidence_score
4519,CHEMBL.COMPOUND:CHEMBL2109293,HGNC:4445,binder,{binder},{ChEMBL},NaN,NaN
4523,CHEMBL.COMPOUND:CHEMBL2109300,HGNC:620,binder,{binder},{ChEMBL},NaN,NaN
4539,CHEMBL.COMPOUND:CHEMBL2109337,HGNC:1633,binder,{binder},{ChEMBL},NaN,NaN
4544,CHEMBL.COMPOUND:CHEMBL2109348,HGNC:7315,binder,{binder},{ChEMBL},NaN,NaN
4560,CHEMBL.COMPOUND:CHEMBL2109367,HGNC:6008,binder,{binder},{ChEMBL},NaN,NaN

In [65]:
experiment_setup[(experiment_setup["drug_concept_id"] == "CHEMBL.COMPOUND:CHEMBL2109293") &
                 (experiment_setup["gene_concept_id"] == "HGNC:4445")]

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
4519,CHEMBL.COMPOUND:CHEMBL2109293,HGNC:4445,binder,{binder},{ChEMBL},{ChEMBL},NaN,NaN,KRN-330,GPA33
4520,CHEMBL.COMPOUND:CHEMBL2109293,HGNC:4445,~PLAIN_INTERACTS,{~NULL},"{TTD, TdgClinicalTrial}","{TTD, ChEMBL, TdgClinicalTrial}",39.152849,3.0,KRN-330,GPA33

In [69]:
experiment_setup[(experiment_setup["mod_type"] == "inhibitor") &
                 ((experiment_setup["mod_sources"].map(len) > 1)) &
                 (experiment_setup["interaction_score"].notna())].drop(columns=["interaction_source_db_name",
                                                                                 "drug_name",
                                                                                "gene_name"])

,drug_concept_id,gene_concept_id,mod_type,interaction_types,mod_sources,interaction_score,evidence_score
6454,CHEMBL.COMPOUND:CHEMBL3544963,HGNC:3942,inhibitor,{inhibitor},"{ChEMBL, CancerCommons}",0.735265,2.0
6812,CHEMBL.COMPOUND:CHEMBL3545401,HGNC:3767,inhibitor,{inhibitor},"{ChEMBL, MyCancerGenome}",0.248590,2.0
6815,CHEMBL.COMPOUND:CHEMBL3545401,HGNC:8803,inhibitor,{inhibitor},"{ChEMBL, MyCancerGenome}",0.342320,2.0
13661,DRUGBANK:DB05169,HGNC:6192,inhibitor,{inhibitor},"{TALC, MyCancerGenome}",0.096853,2.0
13679,DRUGBANK:DB05184,HGNC:3688,inhibitor,{inhibitor},"{TALC, MyCancerGenome}",0.138105,2.0
...,...,...,...,...,...,...,...
37978,RXCUI:477320,HGNC:3236,inhibitor,{inhibitor},"{ChEMBL, MyCancerGenomeClinicalTrial}",0.181263,2.0
40304,RXCUI:6475,HGNC:5295,inhibitor,{inhibitor},"{ChEMBL, GuideToPharmacology}",0.059054,2.0
40895,RXCUI:6826,HGNC:1375,inhibitor,{inhibitor},"{ChEMBL, GuideToPharmacology}",0.803135,2.0
41600,RXCUI:714438,HGNC:6342,inhibitor,{inhibitor},"{ChEMBL, MyCancerGenomeClinicalTrial, TALC, MyCancerGenome}",0.043099,4.0
42158,RXCUI:7426,HGNC:7979,inhibitor,{inhibitor},"{ChEMBL, GuideToPharmacology}",0.144609,2.0

In [44]:
## looking for edges that will get 2nd dp_interacts edge
## (no binder/plain edge to confuse things)

experiment_setup[experiment_setup["mod_type"] == 'agonist']

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
47,CHEMBL.COMPOUND:CHEMBL107430,HGNC:9864,agonist,{agonist},{ChEMBL},{ChEMBL},1.242948,1.0,NRX195183,RARA
113,CHEMBL.COMPOUND:CHEMBL1084173,HGNC:286,agonist,{agonist},{ChEMBL},{ChEMBL},0.404681,1.0,VILANTEROL .ALPHA.-PHENYL CINNAMATE,ADRB2
399,CHEMBL.COMPOUND:CHEMBL1200598,HGNC:3467,agonist,{agonist},{ChEMBL},{ChEMBL},0.080561,1.0,DIETHYLSTILBESTROL DIPHOSPHATE,ESR1
400,CHEMBL.COMPOUND:CHEMBL1200598,HGNC:3468,agonist,{agonist},{ChEMBL},{ChEMBL},0.202340,1.0,DIETHYLSTILBESTROL DIPHOSPHATE,ESR2
412,CHEMBL.COMPOUND:CHEMBL1200949,HGNC:5183,agonist,{agonist},{ChEMBL},{ChEMBL},2.900211,1.0,BETAZOLE HYDROCHLORIDE,HRH2
...,...,...,...,...,...,...,...,...,...,...
44945,RXCUI:9939,HGNC:11330,agonist,{agonist},{ChEMBL},{ChEMBL},0.949160,1.0,SOMATOSTATIN,SSTR1
44946,RXCUI:9939,HGNC:11331,agonist,{agonist},{ChEMBL},{ChEMBL},0.614162,1.0,SOMATOSTATIN,SSTR2
44947,RXCUI:9939,HGNC:11332,agonist,{agonist},{ChEMBL},{ChEMBL},NaN,NaN,SOMATOSTATIN,SSTR3
44949,RXCUI:9939,HGNC:11333,agonist,{agonist},{ChEMBL},{ChEMBL},2.088152,1.0,SOMATOSTATIN,SSTR4
44950,RXCUI:9939,HGNC:11334,agonist,{agonist},{ChEMBL},{ChEMBL},0.949160,1.0,SOMATOSTATIN,SSTR5

In [53]:
pp(experiment_setup[(experiment_setup["drug_concept_id"] == "CHEMBL.COMPOUND:CHEMBL107430") &
                 (experiment_setup["gene_concept_id"] == "HGNC:9864")].to_dict(orient="records")[0])

{'drug_concept_id': 'CHEMBL.COMPOUND:CHEMBL107430',
 'gene_concept_id': 'HGNC:9864',
 'mod_type': 'agonist',
 'interaction_types': {'agonist'},
 'interaction_source_db_name': {'ChEMBL'},
 'mod_sources': {'ChEMBL'},
 'interaction_score': 1.242947584735369,
 'evidence_score': 1.0,
 'drug_name': 'NRX195183',
 'gene_name': 'RARA'}

In [45]:
## NodeNorm maps this ID to Protein

nodenorm_issues = [
    "DRUGBANK:DB12878", 
    "DRUGBANK:DB17983", 
    "DRUGBANK:DB17484",
    "DRUGBANK:DB05451",
]

experiment_setup[(experiment_setup["drug_concept_id"].isin(nodenorm_issues))]

,drug_concept_id,gene_concept_id,mod_type,interaction_types,interaction_source_db_name,mod_sources,interaction_score,evidence_score,drug_name,gene_name
13824,DRUGBANK:DB05451,HGNC:14372,~PLAIN_INTERACTS,{~NULL},{TTD},{TTD},26.101899,1.0,P54,SCYL1
15136,DRUGBANK:DB12878,HGNC:16767,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.257162,1.0,AV-101,GRIN3A
15137,DRUGBANK:DB12878,HGNC:16768,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.286834,1.0,AV-101,GRIN3B
15138,DRUGBANK:DB12878,HGNC:4584,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.149154,1.0,AV-101,GRIN1
15139,DRUGBANK:DB12878,HGNC:4585,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.108082,1.0,AV-101,GRIN2A
15140,DRUGBANK:DB12878,HGNC:4586,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.095611,1.0,AV-101,GRIN2B
15141,DRUGBANK:DB12878,HGNC:4587,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.118376,1.0,AV-101,GRIN2C
15142,DRUGBANK:DB12878,HGNC:4588,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},0.276211,1.0,AV-101,GRIN2D
16365,DRUGBANK:DB17484,HGNC:12680,~PLAIN_INTERACTS,{~NULL},{TTD},{TTD},0.984977,1.0,BI-836880,VEGFA
16423,DRUGBANK:DB17983,HGNC:3430,antibody,{antibody},{MyCancerGenome},{MyCancerGenome},NaN,NaN,MM-111,ERBB2
16424,DRUGBANK:DB17983,HGNC:3430,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,MM-111,ERBB2
16425,DRUGBANK:DB17983,HGNC:3430,~PLAIN_INTERACTS,{~NULL},"{TdgClinicalTrial, TTD}","{TdgClinicalTrial, TTD, MyCancerGenome, ChEMBL}",0.682403,4.0,MM-111,ERBB2
16426,DRUGBANK:DB17983,HGNC:3431,antibody,{antibody},{MyCancerGenome},{MyCancerGenome},NaN,NaN,MM-111,ERBB3
16427,DRUGBANK:DB17983,HGNC:3431,inhibitor,{inhibitor},{ChEMBL},{ChEMBL},NaN,NaN,MM-111,ERBB3
16428,DRUGBANK:DB17983,HGNC:3431,~PLAIN_INTERACTS,{~NULL},{TdgClinicalTrial},"{TdgClinicalTrial, MyCancerGenome, ChEMBL}",1.505879,3.0,MM-111,ERBB3