# Exploring pubtator data for parser

In [1]:
## CX: allows multiple lines of code to print from one code block
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Trying to stop ruff check from using this file
# ruff: noqa

## put in parser (format)
import pathlib
import polars as pl
import html

In [2]:
## useful function: polars version
def check_if_contains(df, column_name, patterns):
    for i in patterns:
        temp = df.filter(pl.col(column_name).str.contains(i, literal=True))
        if temp.shape[0] > 0:
            print(f'{i} count: {temp.shape[0]}')
            
## using literal=True seems to cover special char
delimiters = [",", ";", "-", "_", "|", " "]

<div class="alert alert-block alert-danger">
    
This notebook was originally written using the `2026-03-17` data files from the [FTP site](https://ftp.ncbi.nlm.nih.gov/pub/lu/PubTator3/)

## relation2pubtator3

### Loading file

In [3]:
## using downloaded files 
## paths to raw data files

base_file_path = pathlib.Path.home().joinpath("Desktop", "pubtator_files", "2026_03_17")

relation_path = base_file_path.joinpath("relation2pubtator3.gz")

In [4]:
SOURCE_COLUMNS = ["pmid", "relation", "entity1", "entity2"]

In [5]:
relation_df = pl.read_csv(relation_path,
                          separator="\t",
                          has_header=False,
                          new_columns=SOURCE_COLUMNS,
                         )

In [6]:
relation_df.shape

(39163686, 4)

In [7]:
relation_df.head()

shape: (5, 4)
┌──────────┬───────────┬───────────────────────┬───────────────────────┐
│ pmid     ┆ relation  ┆ entity1               ┆ entity2               │
│ ---      ┆ ---       ┆ ---                   ┆ ---                   │
│ i64      ┆ str       ┆ str                   ┆ str                   │
╞══════════╪═══════════╪═══════════════════════╪═══════════════════════╡
│ 35378878 ┆ associate ┆ Chemical|MESH:D003911 ┆ Disease|MESH:D005334  │
│ 35378880 ┆ treat     ┆ Chemical|MESH:D010866 ┆ Disease|MESH:D060585  │
│ 35378880 ┆ associate ┆ Chemical|MESH:D010866 ┆ Chemical|MESH:D011108 │
│ 35378880 ┆ treat     ┆ Chemical|MESH:D010866 ┆ Disease|MESH:D009181  │
│ 35378880 ┆ treat     ┆ Chemical|MESH:D011108 ┆ Disease|MESH:D060585  │
└──────────┴───────────┴───────────────────────┴───────────────────────┘

### pmid column

i64 (int64) means these values are single IDs w/o prefix.

In [8]:
## add PMID prefixes
##   do early - after merging rows/making set, annoying to add prefix

relation_df = \
relation_df.with_columns(
    pl.concat_str([pl.lit("PMID:"), pl.col("pmid").cast(pl.Utf8)]).alias("pmid"))

relation_df.head()

shape: (5, 4)
┌───────────────┬───────────┬───────────────────────┬───────────────────────┐
│ pmid          ┆ relation  ┆ entity1               ┆ entity2               │
│ ---           ┆ ---       ┆ ---                   ┆ ---                   │
│ str           ┆ str       ┆ str                   ┆ str                   │
╞═══════════════╪═══════════╪═══════════════════════╪═══════════════════════╡
│ PMID:35378878 ┆ associate ┆ Chemical|MESH:D003911 ┆ Disease|MESH:D005334  │
│ PMID:35378880 ┆ treat     ┆ Chemical|MESH:D010866 ┆ Disease|MESH:D060585  │
│ PMID:35378880 ┆ associate ┆ Chemical|MESH:D010866 ┆ Chemical|MESH:D011108 │
│ PMID:35378880 ┆ treat     ┆ Chemical|MESH:D010866 ┆ Disease|MESH:D009181  │
│ PMID:35378880 ┆ treat     ┆ Chemical|MESH:D011108 ┆ Disease|MESH:D060585  │
└───────────────┴───────────┴───────────────────────┴───────────────────────┘

### entity cols: initial processing

Split original "entity" cols into Type + ID

In [9]:
## split entity1/entity2 cols by | into type + ID

DESIRED_COLS = [
    "pmid",
    "relation",
    "entity1_type",
    "entity1_id",
    "entity2_type",
    "entity2_id",
]

relation_df = relation_df \
    .with_columns(
        pl.col("entity1").str.split_exact("|", 1).alias("entity1_parts"),
        pl.col("entity2").str.split_exact("|", 1).alias("entity2_parts"),
    ) \
    .with_columns(
        pl.col("entity1_parts").struct.field("field_0").alias("entity1_type"),
        pl.col("entity1_parts").struct.field("field_1").alias("entity1_id"),
        pl.col("entity2_parts").struct.field("field_0").alias("entity2_type"),
        pl.col("entity2_parts").struct.field("field_1").alias("entity2_id"),
    ) \
    .select(DESIRED_COLS)

In [10]:
relation_df.head()

shape: (5, 6)
┌───────────────┬───────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ pmid          ┆ relation  ┆ entity1_type ┆ entity1_id   ┆ entity2_type ┆ entity2_id   │
│ ---           ┆ ---       ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│ str           ┆ str       ┆ str          ┆ str          ┆ str          ┆ str          │
╞═══════════════╪═══════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ PMID:35378878 ┆ associate ┆ Chemical     ┆ MESH:D003911 ┆ Disease      ┆ MESH:D005334 │
│ PMID:35378880 ┆ treat     ┆ Chemical     ┆ MESH:D010866 ┆ Disease      ┆ MESH:D060585 │
│ PMID:35378880 ┆ associate ┆ Chemical     ┆ MESH:D010866 ┆ Chemical     ┆ MESH:D011108 │
│ PMID:35378880 ┆ treat     ┆ Chemical     ┆ MESH:D010866 ┆ Disease      ┆ MESH:D009181 │
│ PMID:35378880 ┆ treat     ┆ Chemical     ┆ MESH:D011108 ┆ Disease      ┆ MESH:D060585 │
└───────────────┴───────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [82]:
## no null values!

relation_df.null_count()

shape: (1, 6)
┌──────┬──────────┬──────────────┬────────────┬──────────────┬────────────┐
│ pmid ┆ relation ┆ entity1_type ┆ entity1_id ┆ entity2_type ┆ entity2_id │
│ ---  ┆ ---      ┆ ---          ┆ ---        ┆ ---          ┆ ---        │
│ u32  ┆ u32      ┆ u32          ┆ u32        ┆ u32          ┆ u32        │
╞══════╪══════════╪══════════════╪════════════╪══════════════╪════════════╡
│ 0    ┆ 0        ┆ 0            ┆ 0          ┆ 0            ┆ 0          │
└──────┴──────────┴──────────────┴────────────┴──────────────┴────────────┘

In [11]:
## what types are there

relation_df["entity1_type"].value_counts().sort("count", descending=True).show(limit=None)

relation_df["entity2_type"].value_counts().sort("count", descending=True).show(limit=None)

entity1_type,count
str,u32
"""Chemical""",24798573
"""Disease""",10305438
"""Gene""",3765823
"""DNAMutation""",277527
"""ProteinMutation""",13583
"""SNP""",2736
"""Mutation""",6

entity2_type,count
str,u32
"""Gene""",18805153
"""Disease""",12734764
"""Chemical""",6795242
"""ProteinMutation""",566827
"""SNP""",217085
"""DNAMutation""",44069
"""Mutation""",546

Same entity types in entity1 and 2

Next, check the ID format for each type: complex structure? prefixes?

### Current main types/IDs

**Chemical: MESH** - no transforms needed  
Should be single values (no delimiters). Has Translator-standard prefix.


**Disease: MESH, OMIM** - no transforms needed  
Should be single values (no delimiters). Has Translator-standard prefix.

**Gene: no prefix in data, should be NCBIGene** based on paper [normalization section](https://academic.oup.com/nar/article/52/W1/W540/7640526#469437536) and supplementary table 7.  
Should be single values (no delimiters).

In [12]:
delimiters

[',', ';', '-', '_', '|', ' ']

#### Chemical

In [13]:
## look for delimiters - none, single values

print("Entity1\n")

check_if_contains(relation_df.filter((pl.col("entity1_type") == "Chemical")), 
                  "entity1_id", 
                  delimiters)

print("Entity2\n")

check_if_contains(relation_df.filter((pl.col("entity2_type") == "Chemical")), 
                  "entity2_id", 
                  delimiters)

Entity1

Entity2

In [14]:
## look for prefixes that aren't "MESH:" - none

relation_df.filter((pl.col("entity1_type") == "Chemical") &
                   (pl.col("entity1_id").str.starts_with("MESH:").not_()))

relation_df.filter((pl.col("entity2_type") == "Chemical") &
                   (pl.col("entity2_id").str.starts_with("MESH:").not_()))

shape: (0, 6)
┌──────┬──────────┬──────────────┬────────────┬──────────────┬────────────┐
│ pmid ┆ relation ┆ entity1_type ┆ entity1_id ┆ entity2_type ┆ entity2_id │
│ ---  ┆ ---      ┆ ---          ┆ ---        ┆ ---          ┆ ---        │
│ str  ┆ str      ┆ str          ┆ str        ┆ str          ┆ str        │
╞══════╪══════════╪══════════════╪════════════╪══════════════╪════════════╡
└──────┴──────────┴──────────────┴────────────┴──────────────┴────────────┘

shape: (0, 6)
┌──────┬──────────┬──────────────┬────────────┬──────────────┬────────────┐
│ pmid ┆ relation ┆ entity1_type ┆ entity1_id ┆ entity2_type ┆ entity2_id │
│ ---  ┆ ---      ┆ ---          ┆ ---        ┆ ---          ┆ ---        │
│ str  ┆ str      ┆ str          ┆ str        ┆ str          ┆ str        │
╞══════╪══════════╪══════════════╪════════════╪══════════════╪════════════╡
└──────┴──────────┴──────────────┴────────────┴──────────────┴────────────┘

#### Disease

In [15]:
## look for delimiters - none, single values

print("Entity1\n")

check_if_contains(relation_df.filter((pl.col("entity1_type") == "Disease")), 
                  "entity1_id", 
                  delimiters)

print("Entity2\n")

check_if_contains(relation_df.filter((pl.col("entity2_type") == "Disease")), 
                  "entity2_id", 
                  delimiters)

Entity1

Entity2

In [16]:
## look for other prefixes - none

relation_df.filter((pl.col("entity1_type") == "Disease") &
                   (pl.col("entity1_id").str.starts_with("MESH:").not_()) &
                   (pl.col("entity1_id").str.starts_with("OMIM:").not_()))

relation_df.filter((pl.col("entity2_type") == "Disease") &
                   (pl.col("entity2_id").str.starts_with("MESH:").not_()) &
                   (pl.col("entity2_id").str.starts_with("OMIM:").not_()))

shape: (0, 6)
┌──────┬──────────┬──────────────┬────────────┬──────────────┬────────────┐
│ pmid ┆ relation ┆ entity1_type ┆ entity1_id ┆ entity2_type ┆ entity2_id │
│ ---  ┆ ---      ┆ ---          ┆ ---        ┆ ---          ┆ ---        │
│ str  ┆ str      ┆ str          ┆ str        ┆ str          ┆ str        │
╞══════╪══════════╪══════════════╪════════════╪══════════════╪════════════╡
└──────┴──────────┴──────────────┴────────────┴──────────────┴────────────┘

shape: (0, 6)
┌──────┬──────────┬──────────────┬────────────┬──────────────┬────────────┐
│ pmid ┆ relation ┆ entity1_type ┆ entity1_id ┆ entity2_type ┆ entity2_id │
│ ---  ┆ ---      ┆ ---          ┆ ---        ┆ ---          ┆ ---        │
│ str  ┆ str      ┆ str          ┆ str        ┆ str          ┆ str        │
╞══════╪══════════╪══════════════╪════════════╪══════════════╪════════════╡
└──────┴──────────┴──────────────┴────────────┴──────────────┴────────────┘

#### Gene

In [17]:
## look for delimiters - none, single values

print("Entity1\n")

check_if_contains(relation_df.filter((pl.col("entity1_type") == "Gene")), 
                  "entity1_id", 
                  delimiters)

print("Entity2\n")

check_if_contains(relation_df.filter((pl.col("entity2_type") == "Gene")), 
                  "entity2_id", 
                  delimiters)

Entity1

Entity2

In [18]:
## Gene: no prefix (:)

relation_df.filter((pl.col("entity1_type") == "Gene") &
                   (pl.col("entity1_id").str.contains(":", literal=True)))

relation_df.filter((pl.col("entity2_type") == "Gene") &
                   (pl.col("entity2_id").str.contains(":", literal=True)))

shape: (0, 6)
┌──────┬──────────┬──────────────┬────────────┬──────────────┬────────────┐
│ pmid ┆ relation ┆ entity1_type ┆ entity1_id ┆ entity2_type ┆ entity2_id │
│ ---  ┆ ---      ┆ ---          ┆ ---        ┆ ---          ┆ ---        │
│ str  ┆ str      ┆ str          ┆ str        ┆ str          ┆ str        │
╞══════╪══════════╪══════════════╪════════════╪══════════════╪════════════╡
└──────┴──────────┴──────────────┴────────────┴──────────────┴────────────┘

shape: (0, 6)
┌──────┬──────────┬──────────────┬────────────┬──────────────┬────────────┐
│ pmid ┆ relation ┆ entity1_type ┆ entity1_id ┆ entity2_type ┆ entity2_id │
│ ---  ┆ ---      ┆ ---          ┆ ---        ┆ ---          ┆ ---        │
│ str  ┆ str      ┆ str          ┆ str        ┆ str          ┆ str        │
╞══════╪══════════╪══════════════╪════════════╪══════════════╪════════════╡
└──────┴──────────┴──────────────┴────────────┴──────────────┴────────────┘

### Variant types/IDs

[2026-03]

Currently, we don't plan to ingest rows with these types because NodeNorm doesn't include any variant namespaces:
* "DNAMutation"
* "ProteinMutation"
* "SNP"
* "Mutation"

These types seem to fall under what the [paper](https://academic.oup.com/nar/article/52/W1/W540/7640526) calls "genetic variants" and the [FTP site](https://ftp.ncbi.nlm.nih.gov/pub/lu/PubTator3/README.txt) calls "mutations".

#### DNAMutation

The ID values are complex, dict-like.

In [19]:
## notice issue

relation_df.filter((pl.col("entity1_type") == "DNAMutation")).head()

shape: (5, 6)
┌───────────────┬───────────┬──────────────┬─────────────────────────┬──────────────┬──────────────┐
│ pmid          ┆ relation  ┆ entity1_type ┆ entity1_id              ┆ entity2_type ┆ entity2_id   │
│ ---           ┆ ---       ┆ ---          ┆ ---                     ┆ ---          ┆ ---          │
│ str           ┆ str       ┆ str          ┆ str                     ┆ str          ┆ str          │
╞═══════════════╪═══════════╪══════════════╪═════════════════════════╪══════════════╪══════════════╡
│ PMID:35378956 ┆ cause     ┆ DNAMutation  ┆ RS#:568970047;HGVS:c.46 ┆ Disease      ┆ MESH:C579932 │
│               ┆           ┆              ┆ 4G>A;Co…                ┆              ┆              │
│ PMID:35379107 ┆ associate ┆ DNAMutation  ┆ RS#:67376798;HGVS:c.284 ┆ Disease      ┆ MESH:D005770 │
│               ┆           ┆              ┆ 6A>T;Co…                ┆              ┆              │
│ PMID:35379107 ┆ associate ┆ DNAMutation  ┆ RS#:55886062;HGVS:c.167 ┆ Disease      ┆ MESH:D005770 │
│               ┆           ┆              ┆ 9T>G;Co…                ┆              ┆              │
│ PMID:35379107 ┆ associate ┆ DNAMutation  ┆ RS#:3918290;HGVS:c.1905 ┆ Disease      ┆ MESH:D005770 │
│               ┆           ┆              ┆ +1G>A;C…                ┆              ┆              │
│ PMID:35379107 ┆ associate ┆ DNAMutation  ┆ RS#:75017182;HGVS:c.112 ┆ Disease      ┆ MESH:D005770 │
│               ┆           ┆              ┆ 9_5923C…                ┆              ┆              │
└───────────────┴───────────┴──────────────┴─────────────────────────┴──────────────┴──────────────┘

In [20]:
## look at rows with this type

relation_DNAMutation_1 = relation_df.filter((pl.col("entity1_type") == "DNAMutation")) 
relation_DNAMutation_1.shape[0]

relation_DNAMutation_2 = relation_df.filter((pl.col("entity2_type") == "DNAMutation")) 
relation_DNAMutation_2.shape[0]

277527

44069

In [21]:
## look at full values

with pl.Config(fmt_str_lengths=100):
    relation_DNAMutation_1["entity1_id"].head()
    
    relation_DNAMutation_2["entity2_id"].head()

shape: (10,)
Series: 'entity1_id' [str]
[
	"RS#:568970047;HGVS:c.464G>A;CorrespondingGene:57010"
	"RS#:67376798;HGVS:c.2846A>T;CorrespondingGene:1806"
	"RS#:55886062;HGVS:c.1679T>G;CorrespondingGene:1806"
	"RS#:3918290;HGVS:c.1905+1G>A;CorrespondingGene:1806"
	"RS#:75017182;HGVS:c.1129_5923C>G;CorrespondingGene:1806"
	"RS#:1232331611;HGVS:c.3G>A;CorrespondingGene:58497"
	"RS#:1232331611;HGVS:c.3G>A;CorrespondingGene:58497"
	"RS#:1232331611;HGVS:c.3G>A;CorrespondingGene:58497"
	"RS#:1232331611;HGVS:c.3G>A;CorrespondingGene:58497"
	"RS#:1232331611;HGVS:c.3G>A;CorrespondingGene:58497"
]

shape: (10,)
Series: 'entity2_id' [str]
[
	"HGVS:c.2A>A"
	"HGVS:c.2063A>G"
	"HGVS:c.10C>C"
	"HGVS:c.64G>T"
	"HGVS:p.G64S"
	"RS#:1364963022;HGVS:c.273G>A;CorrespondingGene:2099"
	"HGVS:c.143G>A"
	"RS#:747843990;HGVS:c.327G>C;CorrespondingGene:3242"
	"HGVS:c.2A>A;CorrespondingGene:135"
	"RS#:182080362;HGVS:c.76A>T;CorrespondingGene:6878"
]

Some values include [html character entities](https://www.w3schools.com/HTML/html_entities.asp) that start with `&` and **end with `;`**. But `;` is also used as a delimiter between diff key-value pairs.  
**So, transform them into regular char first.**

(Context: noticed when trying to split on `;` and turn into dict -> diff between len and keys)

In [24]:
check_if_contains(relation_DNAMutation_1, "entity1_id", [r"&"])
check_if_contains(relation_DNAMutation_2, "entity2_id", [r"&"])

## look at full values
with pl.Config(fmt_str_lengths=100):
    relation_DNAMutation_1.filter((pl.col("entity1_id").str.contains(r"&")))["entity1_id"].head()
    
    relation_DNAMutation_2.filter((pl.col("entity2_id").str.contains(r"&")))["entity2_id"].head()

& count: 37
& count: 6746

shape: (10,)
Series: 'entity1_id' [str]
[
	"HGVS:c.&lt;IVS2NT+1G>T;CorrespondingGene:6928"
	"HGVS:c.140&lt;=5G>A;CorrespondingGene:1497"
	"HGVS:c.1A&gt;C;CorrespondingGene:1401"
	"HGVS:c.1385A&gt;G"
	"RS#:1449772752;HGVS:c.1157T&gt;C;CorrespondingGene:462"
	"HGVS:c.2A&gt;A"
	"HGVS:c.198A&gt;G"
	"HGVS:c.198A&gt;G"
	"HGVS:c.206C&gt;T;CorrespondingGene:9935"
	"HGVS:c.206C&gt;T;CorrespondingGene:9935"
]

shape: (10,)
Series: 'entity2_id' [str]
[
	"RS#:1447681977;HGVS:c.6464T&gt;C;CorrespondingGene:55714"
	"HGVS:c.941C&gt;T;CorrespondingGene:55714"
	"HGVS:c.34311A&gt;C;CorrespondingGene:672"
	"HGVS:c.2A&gt;A;CorrespondingGene:135"
	"HGVS:c.2A&gt;A;CorrespondingGene:135"
	"HGVS:c.2A&gt;A;CorrespondingGene:135"
	"HGVS:c.2A&gt;A;CorrespondingGene:135"
	"HGVS:c.940G&gt;T;CorrespondingGene:2070"
	"HGVS:c.548C&gt;G;CorrespondingGene:2070"
	"HGVS:c.548C&gt;G;CorrespondingGene:2070"
]

In [25]:
## using html package on a string

html.unescape("RS#:1447681977;HGVS:c.6464T&gt;C;CorrespondingGene:55714")

'RS#:1447681977;HGVS:c.6464T>C;CorrespondingGene:55714'

**NOTE**: Should be okay to do this col-wise in whole df: shouldn't harm values

In [26]:
## col-wise: turn these into regular strings with html package

relation_DNAMutation_1 = relation_DNAMutation_1.with_columns(
    pl.col("entity1_id")
    .map_elements(html.unescape, return_dtype=pl.Utf8)
    .alias("entity1_id")
)

relation_DNAMutation_2 = relation_DNAMutation_2.with_columns(
    pl.col("entity2_id")
    .map_elements(html.unescape, return_dtype=pl.Utf8)
    .alias("entity2_id")
)

In [28]:
## check: if nothing prints, html character entities are gone

check_if_contains(relation_DNAMutation_1, "entity1_id", [r"&"])
check_if_contains(relation_DNAMutation_2, "entity2_id", [r"&"])

In [30]:
## check for other html strings. url-encoded: %20, tags: </b>
## if nothing prints, nothing found

other_html = [r"%", r"</"]

check_if_contains(relation_DNAMutation_1, "entity1_id", other_html)
check_if_contains(relation_DNAMutation_2, "entity2_id", other_html)

EDA: Inspecting the possible keys by turning values into dicts.

In [28]:
dnamutation_keys = set()
longest = 0

## entity 1
for s in relation_DNAMutation_1["entity1_id"]:
    n_items = len(s.split(";"))
    if n_items > longest:
        longest = n_items
    if n_items > 3:
        print(s)
    
    temp = dict(item.split(":", 1) for item in s.split(";") if ":" in item)
    
    dnamutation_keys.update(temp.keys())

In [29]:
dnamutation_keys

longest

temp

{'CorrespondingGene', 'HGVS', 'RS#'}

3

{'HGVS': 'c.3A>T'}

In [30]:
## entity 2
for s in relation_DNAMutation_2["entity2_id"]:
    n_items = len(s.split(";"))
    if n_items > longest:
        longest = n_items
    if n_items > 3:
        print(s)
    
    temp = dict(item.split(":", 1) for item in s.split(";") if ":" in item)
    
    dnamutation_keys.update(temp.keys())

In [31]:
dnamutation_keys

longest

temp

{'CorrespondingGene', 'HGVS', 'RS#'}

3

{'RS#': '1801133', 'HGVS': 'c.677C>T', 'CorrespondingGene': '4524'}

[2026-03]

So there's 3 possible keys:
* `RS#`: dbSNP ID? If so, [missing 'rs' in value](https://bioregistry.io/registry/dbsnp)
* `CorrespondingGene`: no prefix in data, should be NCBIGene ID
* `HGVS`: [nomenclature for variant description](https://hgvs-nomenclature.org/stable/), not regular database ID. And **these are NOT complete, standard values** - [missing sequence and transcript ID](https://hgvs-nomenclature.org/stable/recommendations/DNA/substitution/)

**NOTE**: The whole ID string can be used in group-by/merging rows. Then this dict parsing can be done in `transform_record` step.

Easier to code, preprocessing doesn't depend on knowing keys, less iteration over whole df.

Reviewed possible multi-value delimiters: based on a quick skim, all values found were part of `HGVS` values.

In [31]:
delimiters

[',', ';', '-', '_', '|', ' ']

In [32]:
## do a delimiter check on a more limited set
## if nothing prints, nothing found

var_delimiters = [",", "-", "_", "|", " "]

check_if_contains(relation_DNAMutation_1, "entity1_id", var_delimiters)
check_if_contains(relation_DNAMutation_2, "entity2_id", var_delimiters)

, count: 3271
- count: 39326
_ count: 17287
, count: 807
- count: 4583
_ count: 1069

In [37]:
## look at full values
with pl.Config(fmt_str_lengths=100):
    relation_DNAMutation_1.filter((pl.col("entity1_id").str.contains("_")))["entity1_id"].head()

shape: (10,)
Series: 'entity1_id' [str]
[
	"RS#:75017182;HGVS:c.1129_5923C>G;CorrespondingGene:1806"
	"HGVS:g.25679_25679delA;CorrespondingGene:1727"
	"HGVS:c.824_825insC;CorrespondingGene:1727"
	"HGVS:c.824_825insC;CorrespondingGene:1727"
	"HGVS:g.25679_25679delA;CorrespondingGene:1727"
	"HGVS:c.824_825insC;CorrespondingGene:1727"
	"HGVS:g.25679_25679delA;CorrespondingGene:1727"
	"HGVS:c.317_320dupAGTG;CorrespondingGene:1161"
	"HGVS:c.343_344delCT;CorrespondingGene:268"
	"HGVS:c.2102_2103insA;CorrespondingGene:10577"
]

#### ProteinMutation - NOT DONE

The ID values are complex, dict-like (look like DNAMutation's).

In [43]:
## quick look

relation_df.filter((pl.col("entity1_type") == "ProteinMutation")).head()

shape: (5, 6)
┌───────────────┬───────────┬─────────────────┬─────────────────┬─────────────────┬────────────────┐
│ pmid          ┆ relation  ┆ entity1_type    ┆ entity1_id      ┆ entity2_type    ┆ entity2_id     │
│ ---           ┆ ---       ┆ ---             ┆ ---             ┆ ---             ┆ ---            │
│ str           ┆ str       ┆ str             ┆ str             ┆ str             ┆ str            │
╞═══════════════╪═══════════╪═════════════════╪═════════════════╪═════════════════╪════════════════╡
│ PMID:35378893 ┆ associate ┆ ProteinMutation ┆ HGVS:p.G323D;Co ┆ ProteinMutation ┆ HGVS:p.Y137H;C │
│               ┆           ┆                 ┆ rrespondingGene ┆                 ┆ orrespondingGe │
│               ┆           ┆                 ┆ …               ┆                 ┆ ne…            │
│ PMID:34903070 ┆ associate ┆ ProteinMutation ┆ RS#:12934922;HG ┆ ProteinMutation ┆ RS#:7501331;HG │
│               ┆           ┆                 ┆ VS:p.R267S;Corr ┆                 ┆ VS:p.A379V;Cor │
│               ┆           ┆                 ┆ …               ┆                 ┆ re…            │
│ PMID:34050359 ┆ associate ┆ ProteinMutation ┆ RS#:113488022;H ┆ ProteinMutation ┆ RS#:760043106; │
│               ┆           ┆                 ┆ GVS:p.V600E;Cor ┆                 ┆ HGVS:p.I195N;C │
│               ┆           ┆                 ┆ …               ┆                 ┆ or…            │
│ PMID:34121011 ┆ associate ┆ ProteinMutation ┆ HGVS:p.K4326E;C ┆ ProteinMutation ┆ HGVS:p.L1412Kf │
│               ┆           ┆                 ┆ orrespondingGen ┆                 ┆ sX16;Correspon │
│               ┆           ┆                 ┆ …               ┆                 ┆ di…            │
│ PMID:29625985 ┆ associate ┆ ProteinMutation ┆ HGVS:p.H336R;Co ┆ ProteinMutation ┆ HGVS:p.L541P;C │
│               ┆           ┆                 ┆ rrespondingGene ┆                 ┆ orrespondingGe │
│               ┆           ┆                 ┆ …               ┆                 ┆ ne…            │
└───────────────┴───────────┴─────────────────┴─────────────────┴─────────────────┴────────────────┘

#### SNP - NOT DONE

The ID values are complex, dict-like (look like DNAMutation's, maybe w/o HGVS?).

In [44]:
## quick look

relation_df.filter((pl.col("entity1_type") == "SNP")).head()

shape: (5, 6)
┌───────────────┬───────────┬──────────────┬────────────────────┬──────────────┬───────────────────┐
│ pmid          ┆ relation  ┆ entity1_type ┆ entity1_id         ┆ entity2_type ┆ entity2_id        │
│ ---           ┆ ---       ┆ ---          ┆ ---                ┆ ---          ┆ ---               │
│ str           ┆ str       ┆ str          ┆ str                ┆ str          ┆ str               │
╞═══════════════╪═══════════╪══════════════╪════════════════════╪══════════════╪═══════════════════╡
│ PMID:21127300 ┆ associate ┆ SNP          ┆ RS#:10455872;Corre ┆ SNP          ┆ RS#:3123629;Corre │
│               ┆           ┆              ┆ spondingGene…      ┆              ┆ spondingGene:…    │
│ PMID:35998284 ┆ associate ┆ SNP          ┆ RS#:2241766;Corres ┆ SNP          ┆ RS#:3774261;Corre │
│               ┆           ┆              ┆ pondingGene:…      ┆              ┆ spondingGene:…    │
│ PMID:35617280 ┆ associate ┆ SNP          ┆ RS#:9527025;Corres ┆ SNP          ┆ RS#:9536314;Corre │
│               ┆           ┆              ┆ pondingGene:…      ┆              ┆ spondingGene:…    │
│ PMID:27951722 ┆ associate ┆ SNP          ┆ RS#:2020903;Corres ┆ SNP          ┆ RS#:4646034;Corre │
│               ┆           ┆              ┆ pondingGene:…      ┆              ┆ spondingGene:…    │
│ PMID:36723865 ┆ associate ┆ SNP          ┆ RS#:2812377;Corres ┆ SNP          ┆ RS#:3136658;Corre │
│               ┆           ┆              ┆ pondingGene:…      ┆              ┆ spondingGene:…    │
└───────────────┴───────────┴──────────────┴────────────────────┴──────────────┴───────────────────┘

#### Mutation - NOT DONE

Looks like a variant description, not an ID

In [45]:
## quick look

relation_df.filter((pl.col("entity1_type") == "Mutation")).head()

shape: (5, 6)
┌───────────────┬───────────┬──────────────┬──────────────────┬─────────────────┬──────────────────┐
│ pmid          ┆ relation  ┆ entity1_type ┆ entity1_id       ┆ entity2_type    ┆ entity2_id       │
│ ---           ┆ ---       ┆ ---          ┆ ---              ┆ ---             ┆ ---              │
│ str           ┆ str       ┆ str          ┆ str              ┆ str             ┆ str              │
╞═══════════════╪═══════════╪══════════════╪══════════════════╪═════════════════╪══════════════════╡
│ PMID:32468074 ┆ associate ┆ Mutation     ┆ Chr8:18765448-18 ┆ ProteinMutation ┆ RS#:113488022;HG │
│               ┆           ┆              ┆ 804898del        ┆                 ┆ VS:p.V600E;Cor…  │
│ PMID:32468074 ┆ associate ┆ Mutation     ┆ Chr5:161330882-1 ┆ ProteinMutation ┆ RS#:113488022;HG │
│               ┆           ┆              ┆ 61336769del      ┆                 ┆ VS:p.V600E;Cor…  │
│ PMID:32468074 ┆ associate ┆ Mutation     ┆ Chr9:22046750-22 ┆ ProteinMutation ┆ RS#:113488022;HG │
│               ┆           ┆              ┆ 097364dup        ┆                 ┆ VS:p.V600E;Cor…  │
│ PMID:32468074 ┆ associate ┆ Mutation     ┆ Chr5:161330882-1 ┆ ProteinMutation ┆ RS#:113488022;HG │
│               ┆           ┆              ┆ 61336769del      ┆                 ┆ VS:p.V600E;Cor…  │
│ PMID:32468074 ┆ associate ┆ Mutation     ┆ Chr8:18765448-18 ┆ ProteinMutation ┆ RS#:113488022;HG │
│               ┆           ┆              ┆ 804898del        ┆                 ┆ VS:p.V600E;Cor…  │
└───────────────┴───────────┴──────────────┴──────────────────┴─────────────────┴──────────────────┘

### relation/combos

In [38]:
relation_df["relation"].value_counts().sort("count", descending=True).show(limit=None)

relation,count
str,u32
"""associate""",18173612
"""treat""",7149232
"""negative_correlate""",4006623
"""cause""",3677170
"""positive_correlate""",3394019
"""stimulate""",770147
"""inhibit""",609787
"""cotreat""",552752
"""compare""",530067
"""interact""",259008
"""prevent""",33746
"""drug_interact""",7523

In [39]:
relation_df

shape: (39_163_686, 6)
┌───────────────┬───────────────────┬──────────────┬─────────────────┬──────────────┬──────────────┐
│ pmid          ┆ relation          ┆ entity1_type ┆ entity1_id      ┆ entity2_type ┆ entity2_id   │
│ ---           ┆ ---               ┆ ---          ┆ ---             ┆ ---          ┆ ---          │
│ str           ┆ str               ┆ str          ┆ str             ┆ str          ┆ str          │
╞═══════════════╪═══════════════════╪══════════════╪═════════════════╪══════════════╪══════════════╡
│ PMID:35378878 ┆ associate         ┆ Chemical     ┆ MESH:D003911    ┆ Disease      ┆ MESH:D005334 │
│ PMID:35378880 ┆ treat             ┆ Chemical     ┆ MESH:D010866    ┆ Disease      ┆ MESH:D060585 │
│ PMID:35378880 ┆ associate         ┆ Chemical     ┆ MESH:D010866    ┆ Chemical     ┆ MESH:D011108 │
│ PMID:35378880 ┆ treat             ┆ Chemical     ┆ MESH:D010866    ┆ Disease      ┆ MESH:D009181 │
│ PMID:35378880 ┆ treat             ┆ Chemical     ┆ MESH:D011108    ┆ Disease      ┆ MESH:D060585 │
│ …             ┆ …                 ┆ …            ┆ …               ┆ …            ┆ …            │
│ PMID:41822489 ┆ treat             ┆ Chemical     ┆ MESH:D000077150 ┆ Disease      ┆ MESH:D013274 │
│ PMID:41822489 ┆ cotreat           ┆ Chemical     ┆ MESH:D000077150 ┆ Chemical     ┆ MESH:D002955 │
│ PMID:41822489 ┆ negative_correlat ┆ Chemical     ┆ MESH:D002955    ┆ Gene         ┆ 9825         │
│               ┆ e                 ┆              ┆                 ┆              ┆              │
│ PMID:41822489 ┆ treat             ┆ Chemical     ┆ MESH:D000077143 ┆ Disease      ┆ MESH:D013274 │
│ PMID:41822489 ┆ treat             ┆ Chemical     ┆ MESH:D005472    ┆ Disease      ┆ MESH:D013274 │
└───────────────┴───────────────────┴──────────────┴─────────────────┴──────────────┴──────────────┘

In [50]:
triple_cols = ["entity1_type", "relation", "entity2_type"]

combo_counts = (
    relation_df.group_by(triple_cols)
      .len()
)

In [51]:
combo_counts.sort(triple_cols).show(limit=None)

entity1_type,relation,entity2_type,len
str,str,str,u32
"""Chemical""","""associate""","""Chemical""",3012947
"""Chemical""","""associate""","""DNAMutation""",15682
"""Chemical""","""associate""","""Disease""",2125918
"""Chemical""","""associate""","""Gene""",2116211
"""Chemical""","""associate""","""ProteinMutation""",60623
"""Chemical""","""associate""","""SNP""",11069
"""Chemical""","""cause""","""Disease""",3198130
"""Chemical""","""compare""","""Chemical""",530067
"""Chemical""","""cotreat""","""Chemical""",552752
"""Chemical""","""drug_interact""","""Chemical""",7523
"""Chemical""","""inhibit""","""DNAMutation""",6265
"""Chemical""","""inhibit""","""Mutation""",1
"""Chemical""","""inhibit""","""ProteinMutation""",27371
"""Chemical""","""inhibit""","""SNP""",2158
"""Chemical""","""interact""","""Chemical""",10561
"""Chemical""","""interact""","""DNAMutation""",227
"""Chemical""","""interact""","""Gene""",46206
"""Chemical""","""interact""","""ProteinMutation""",957
"""Chemical""","""interact""","""SNP""",2
"""Chemical""","""negative_correlate""","""Chemical""",1628691
"""Chemical""","""negative_correlate""","""Gene""",1916188
"""Chemical""","""positive_correlate""","""Chemical""",1052701
"""Chemical""","""positive_correlate""","""Gene""",1297821
"""Chemical""","""stimulate""","""DNAMutation""",7416
"""Chemical""","""stimulate""","""ProteinMutation""",17866
"""Chemical""","""stimulate""","""SNP""",3988
"""Chemical""","""treat""","""Disease""",7149232
"""DNAMutation""","""associate""","""DNAMutation""",6316
"""DNAMutation""","""associate""","""Disease""",107972
"""DNAMutation""","""associate""","""ProteinMutation""",8803
"""DNAMutation""","""associate""","""SNP""",924
"""DNAMutation""","""cause""","""Disease""",144818
"""DNAMutation""","""prevent""","""Disease""",8694
"""Disease""","""associate""","""DNAMutation""",3085
"""Disease""","""associate""","""Gene""",8348035
"""Disease""","""associate""","""Mutation""",341
"""Disease""","""associate""","""ProteinMutation""",203907
"""Disease""","""associate""","""SNP""",75927
"""Disease""","""cause""","""DNAMutation""",4919
"""Disease""","""cause""","""Mutation""",194
"""Disease""","""cause""","""ProteinMutation""",225585
"""Disease""","""cause""","""SNP""",103524
"""Disease""","""inhibit""","""Gene""",573992
"""Disease""","""prevent""","""DNAMutation""",141
"""Disease""","""prevent""","""Mutation""",10
"""Disease""","""prevent""","""ProteinMutation""",9068
"""Disease""","""prevent""","""SNP""",15833
"""Disease""","""stimulate""","""Gene""",740877
"""Gene""","""associate""","""Gene""",2059527
"""Gene""","""interact""","""Gene""",201055
"""Gene""","""negative_correlate""","""Gene""",461744
"""Gene""","""positive_correlate""","""Gene""",1043497
"""Mutation""","""associate""","""ProteinMutation""",6
"""ProteinMutation""","""associate""","""DNAMutation""",15
"""ProteinMutation""","""associate""","""ProteinMutation""",12639
"""ProteinMutation""","""associate""","""SNP""",929
"""SNP""","""associate""","""DNAMutation""",3
"""SNP""","""associate""","""ProteinMutation""",2
"""SNP""","""associate""","""SNP""",2731

### Filter out variant types

In [53]:
EXCLUDED_ENTITY_TYPES = ["DNAMutation", "ProteinMutation", "SNP", "Mutation"]

In [54]:
relation_df_filtered = relation_df.filter(
            ~(
                pl.col("entity1_type").is_in(EXCLUDED_ENTITY_TYPES)
                | pl.col("entity2_type").is_in(EXCLUDED_ENTITY_TYPES)
            )
        )

In [56]:
relation_df_filtered.shape[0]

relation_df_filtered.shape[0] / relation_df.shape[0]

38073675

0.9721678138263083

In [57]:
combo_counts_filtered = (
    relation_df_filtered.group_by(triple_cols)
      .len()
)

In [59]:
combo_counts_filtered.sort(["relation", "entity1_type", "entity2_type"]) \
    .select(["entity1_type", "relation", "entity2_type", "len"]) \
    .show(limit=None)

entity1_type,relation,entity2_type,len
str,str,str,u32
"""Chemical""","""associate""","""Chemical""",3012947
"""Chemical""","""associate""","""Disease""",2125918
"""Chemical""","""associate""","""Gene""",2116211
"""Disease""","""associate""","""Gene""",8348035
"""Gene""","""associate""","""Gene""",2059527
"""Chemical""","""cause""","""Disease""",3198130
"""Chemical""","""compare""","""Chemical""",530067
"""Chemical""","""cotreat""","""Chemical""",552752
"""Chemical""","""drug_interact""","""Chemical""",7523
"""Disease""","""inhibit""","""Gene""",573992
"""Chemical""","""interact""","""Chemical""",10561
"""Chemical""","""interact""","""Gene""",46206
"""Gene""","""interact""","""Gene""",201055
"""Chemical""","""negative_correlate""","""Chemical""",1628691
"""Chemical""","""negative_correlate""","""Gene""",1916188
"""Gene""","""negative_correlate""","""Gene""",461744
"""Chemical""","""positive_correlate""","""Chemical""",1052701
"""Chemical""","""positive_correlate""","""Gene""",1297821
"""Gene""","""positive_correlate""","""Gene""",1043497
"""Disease""","""stimulate""","""Gene""",740877
"""Chemical""","""treat""","""Disease""",7149232

In [68]:
combo_counts_filtered["relation"].value_counts().sort("relation").show(limit=None)

relation,count
str,u32
"""associate""",5
"""cause""",1
"""compare""",1
"""cotreat""",1
"""drug_interact""",1
"""inhibit""",1
"""interact""",3
"""negative_correlate""",3
"""positive_correlate""",3
"""stimulate""",1
"""treat""",1

### EDA: Merge by ID 1, relation, ID 2 combos

In [70]:
GROUP_BY_COLUMNS = ["entity1_id", "relation", "entity2_id"]
SET_COLUMNS = ["pmid", "entity1_type", "entity2_type"]

In [74]:
merge1 = (relation_df_filtered
        .group_by(GROUP_BY_COLUMNS)
        .agg([
            pl.col(column).drop_nulls().unique().sort().alias(f"{column}_set")
            for column in SET_COLUMNS
        ]))

In [75]:
merge1

shape: (11_335_397, 6)
┌────────────────┬────────────────┬──────────────┬────────────────┬────────────────┬───────────────┐
│ entity1_id     ┆ relation       ┆ entity2_id   ┆ pmid_set       ┆ entity1_type_s ┆ entity2_type_ │
│ ---            ┆ ---            ┆ ---          ┆ ---            ┆ et             ┆ set           │
│ str            ┆ str            ┆ str          ┆ list[str]      ┆ ---            ┆ ---           │
│                ┆                ┆              ┆                ┆ list[str]      ┆ list[str]     │
╞════════════════╪════════════════╪══════════════╪════════════════╪════════════════╪═══════════════╡
│ 10468          ┆ associate      ┆ 3161         ┆ ["PMID:4127118 ┆ ["Gene"]       ┆ ["Gene"]      │
│                ┆                ┆              ┆ 2"]            ┆                ┆               │
│ MESH:D002186   ┆ associate      ┆ MESH:D019840 ┆ ["PMID:3545098 ┆ ["Chemical"]   ┆ ["Chemical"]  │
│                ┆                ┆              ┆ 0"]            ┆                ┆               │
│ MESH:C585131   ┆ treat          ┆ MESH:D010146 ┆ ["PMID:3848462 ┆ ["Chemical"]   ┆ ["Disease"]   │
│                ┆                ┆              ┆ 7"]            ┆                ┆               │
│ MESH:C00062676 ┆ associate      ┆ 6241         ┆ ["PMID:3002750 ┆ ["Chemical"]   ┆ ["Gene"]      │
│ 6              ┆                ┆              ┆ 2"]            ┆                ┆               │
│ MESH:C112381   ┆ negative_corre ┆ MESH:D016572 ┆ ["PMID:2549977 ┆ ["Chemical"]   ┆ ["Chemical"]  │
│                ┆ late           ┆              ┆ ",             ┆                ┆               │
│                ┆                ┆              ┆ "PMID:2731309… ┆                ┆               │
│ …              ┆ …              ┆ …            ┆ …              ┆ …              ┆ …             │
│ MESH:D014867   ┆ associate      ┆ 92745        ┆ ["PMID:2306457 ┆ ["Chemical"]   ┆ ["Gene"]      │
│                ┆                ┆              ┆ "]             ┆                ┆               │
│ MESH:C039602   ┆ associate      ┆ 10891        ┆ ["PMID:3874933 ┆ ["Chemical"]   ┆ ["Gene"]      │
│                ┆                ┆              ┆ 2"]            ┆                ┆               │
│ MESH:D010869   ┆ positive_corre ┆ 25645        ┆ ["PMID:1252207 ┆ ["Chemical"]   ┆ ["Gene"]      │
│                ┆ late           ┆              ┆ 8",            ┆                ┆               │
│                ┆                ┆              ┆ "PMID:194298…  ┆                ┆               │
│ MESH:C413206   ┆ associate      ┆ MESH:C491966 ┆ ["PMID:1095653 ┆ ["Chemical"]   ┆ ["Chemical"]  │
│                ┆                ┆              ┆ 3",            ┆                ┆               │
│                ┆                ┆              ┆ "PMID:146643…  ┆                ┆               │
│ MESH:C516667   ┆ treat          ┆ MESH:D050398 ┆ ["PMID:2346167 ┆ ["Chemical"]   ┆ ["Disease"]   │
│                ┆                ┆              ┆ 2",            ┆                ┆               │
│                ┆                ┆              ┆ "PMID:384863…  ┆                ┆               │
└────────────────┴────────────────┴──────────────┴────────────────┴────────────────┴───────────────┘

In [84]:
merge1.filter(pl.col("entity1_type_set").list.len() > 1)

shape: (4, 6)
┌──────────────┬───────────┬────────────┬───────────────────┬───────────────────┬──────────────────┐
│ entity1_id   ┆ relation  ┆ entity2_id ┆ pmid_set          ┆ entity1_type_set  ┆ entity2_type_set │
│ ---          ┆ ---       ┆ ---        ┆ ---               ┆ ---               ┆ ---              │
│ str          ┆ str       ┆ str        ┆ list[str]         ┆ list[str]         ┆ list[str]        │
╞══════════════╪═══════════╪════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ MESH:C562477 ┆ associate ┆ 1571       ┆ ["PMID:10851284", ┆ ["Chemical",      ┆ ["Gene"]         │
│              ┆           ┆            ┆ "PMID:154567…     ┆ "Disease"]        ┆                  │
│ MESH:C536778 ┆ associate ┆ 7124       ┆ ["PMID:18462845", ┆ ["Chemical",      ┆ ["Gene"]         │
│              ┆           ┆            ┆ "PMID:416405…     ┆ "Disease"]        ┆                  │
│ MESH:C564403 ┆ associate ┆ 56997      ┆ ["PMID:18319072", ┆ ["Chemical",      ┆ ["Gene"]         │
│              ┆           ┆            ┆ "PMID:240489…     ┆ "Disease"]        ┆                  │
│ MESH:C564403 ┆ associate ┆ 2110       ┆ ["PMID:17412732", ┆ ["Chemical",      ┆ ["Gene"]         │
│              ┆           ┆            ┆ "PMID:188368…     ┆ "Disease"]        ┆                  │
└──────────────┴───────────┴────────────┴───────────────────┴───────────────────┴──────────────────┘

In [85]:
merge1.filter(pl.col("entity2_type_set").list.len() > 1)

shape: (1, 6)
┌──────────────┬───────────┬──────────────┬──────────────────┬──────────────────┬──────────────────┐
│ entity1_id   ┆ relation  ┆ entity2_id   ┆ pmid_set         ┆ entity1_type_set ┆ entity2_type_set │
│ ---          ┆ ---       ┆ ---          ┆ ---              ┆ ---              ┆ ---              │
│ str          ┆ str       ┆ str          ┆ list[str]        ┆ list[str]        ┆ list[str]        │
╞══════════════╪═══════════╪══════════════╪══════════════════╪══════════════════╪══════════════════╡
│ MESH:C024989 ┆ associate ┆ MESH:C564403 ┆ ["PMID:17442627" ┆ ["Chemical"]     ┆ ["Chemical",     │
│              ┆           ┆              ┆ , "PMID:183873…  ┆                  ┆ "Disease"]       │
└──────────────┴───────────┴──────────────┴──────────────────┴──────────────────┴──────────────────┘

In [89]:
multi_types = merge1.filter((pl.col("entity1_type_set").list.len() > 1) |
                            (pl.col("entity2_type_set").list.len() > 1))

multi_types

shape: (5, 6)
┌──────────────┬───────────┬──────────────┬──────────────────┬──────────────────┬──────────────────┐
│ entity1_id   ┆ relation  ┆ entity2_id   ┆ pmid_set         ┆ entity1_type_set ┆ entity2_type_set │
│ ---          ┆ ---       ┆ ---          ┆ ---              ┆ ---              ┆ ---              │
│ str          ┆ str       ┆ str          ┆ list[str]        ┆ list[str]        ┆ list[str]        │
╞══════════════╪═══════════╪══════════════╪══════════════════╪══════════════════╪══════════════════╡
│ MESH:C562477 ┆ associate ┆ 1571         ┆ ["PMID:10851284" ┆ ["Chemical",     ┆ ["Gene"]         │
│              ┆           ┆              ┆ , "PMID:154567…  ┆ "Disease"]       ┆                  │
│ MESH:C536778 ┆ associate ┆ 7124         ┆ ["PMID:18462845" ┆ ["Chemical",     ┆ ["Gene"]         │
│              ┆           ┆              ┆ , "PMID:416405…  ┆ "Disease"]       ┆                  │
│ MESH:C024989 ┆ associate ┆ MESH:C564403 ┆ ["PMID:17442627" ┆ ["Chemical"]     ┆ ["Chemical",     │
│              ┆           ┆              ┆ , "PMID:183873…  ┆                  ┆ "Disease"]       │
│ MESH:C564403 ┆ associate ┆ 56997        ┆ ["PMID:18319072" ┆ ["Chemical",     ┆ ["Gene"]         │
│              ┆           ┆              ┆ , "PMID:240489…  ┆ "Disease"]       ┆                  │
│ MESH:C564403 ┆ associate ┆ 2110         ┆ ["PMID:17412732" ┆ ["Chemical",     ┆ ["Gene"]         │
│              ┆           ┆              ┆ , "PMID:188368…  ┆ "Disease"]       ┆                  │
└──────────────┴───────────┴──────────────┴──────────────────┴──────────────────┴──────────────────┘

[2026-03]

Looks like there's some MESH IDs assigned to Chemical + Disease.

It doesn't really matter:
* "associate" won't map to a predicate with sub/obj category restrictions
* NodeNorming will fix the category anyways. 

Looking at them...
* [MESH:C564403](https://id.nlm.nih.gov/mesh/C564403.html): Coenzyme Q10 Deficiency => Disease
* [MESH:C562477](https://id.nlm.nih.gov/mesh/C562477.html): Halothane Hepatitis => Disease
* [MESH:C536778](https://id.nlm.nih.gov/mesh/C536778.html): Systemic carnitine deficiency => Disease

So...try only keeping "first" value for entity type cols.

In [87]:
merge2 = (relation_df_filtered
        .group_by(GROUP_BY_COLUMNS)
        .agg(
            pl.col("pmid").drop_nulls().unique().sort().alias("pmid_set"),
            pl.col("entity1_type").first().alias("entity1_type"),
            pl.col("entity2_type").first().alias("entity2_type"),
        ))

In [90]:
## check those same rows

merge2.join(multi_types, on=GROUP_BY_COLUMNS, how="semi")

shape: (5, 6)
┌──────────────┬───────────┬──────────────┬───────────────────┬──────────────┬──────────────┐
│ entity1_id   ┆ relation  ┆ entity2_id   ┆ pmid_set          ┆ entity1_type ┆ entity2_type │
│ ---          ┆ ---       ┆ ---          ┆ ---               ┆ ---          ┆ ---          │
│ str          ┆ str       ┆ str          ┆ list[str]         ┆ str          ┆ str          │
╞══════════════╪═══════════╪══════════════╪═══════════════════╪══════════════╪══════════════╡
│ MESH:C562477 ┆ associate ┆ 1571         ┆ ["PMID:10851284", ┆ Chemical     ┆ Gene         │
│              ┆           ┆              ┆ "PMID:154567…     ┆              ┆              │
│ MESH:C024989 ┆ associate ┆ MESH:C564403 ┆ ["PMID:17442627", ┆ Chemical     ┆ Disease      │
│              ┆           ┆              ┆ "PMID:183873…     ┆              ┆              │
│ MESH:C536778 ┆ associate ┆ 7124         ┆ ["PMID:18462845", ┆ Chemical     ┆ Gene         │
│              ┆           ┆              ┆ "PMID:416405…     ┆              ┆              │
│ MESH:C564403 ┆ associate ┆ 56997        ┆ ["PMID:18319072", ┆ Disease      ┆ Gene         │
│              ┆           ┆              ┆ "PMID:240489…     ┆              ┆              │
│ MESH:C564403 ┆ associate ┆ 2110         ┆ ["PMID:17412732", ┆ Disease      ┆ Gene         │
│              ┆           ┆              ┆ "PMID:188368…     ┆              ┆              │
└──────────────┴───────────┴──────────────┴───────────────────┴──────────────┴──────────────┘